-- +goose Up
-- Create "relation_evidence" table
CREATE TABLE "silver"."relation_evidence" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "from_document_id" bigint NOT NULL, "from_section_id" bigint NULL, "target_ref_id" bigint NOT NULL, "evidence_key" text NOT NULL, "evidence_kind" text NOT NULL, "relation_type" text NOT NULL, "relation_type_raw" integer NULL, "operator" text NOT NULL DEFAULT '', "target_text" text NOT NULL, "target_citation" text NULL, "citation" text NOT NULL DEFAULT '', "snippet" text NOT NULL DEFAULT '', "source" text NOT NULL DEFAULT '', "source_authority" text NOT NULL DEFAULT '', "confidence" double precision NOT NULL DEFAULT 0, "promoted" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "uq_silver_relation_ev" UNIQUE ("from_document_id", "evidence_key"), CONSTRAINT "fk_silver_relation_ev_from_doc" FOREIGN KEY ("from_document_id") REFERENCES "silver"."document" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_silver_relation_ev_from_sec" FOREIGN KEY ("from_section_id") REFERENCES "silver"."document_section" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "fk_silver_relation_ev_target" FOREIGN KEY ("target_ref_id") REFERENCES "silver"."doc_ref" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "chk_silver_relation_ev_kind" CHECK (evidence_kind = ANY (ARRAY['structured_relation'::text, 'model_classification'::text, 'weak_relation'::text])));
-- Create index "idx_silver_relation_ev_from" to table: "relation_evidence"
CREATE INDEX "idx_silver_relation_ev_from" ON "silver"."relation_evidence" ("from_document_id");
-- Create index "idx_silver_relation_ev_target" to table: "relation_evidence"
CREATE INDEX "idx_silver_relation_ev_target" ON "silver"."relation_evidence" ("target_ref_id");
-- Create index "idx_silver_relation_ev_type" to table: "relation_evidence"
CREATE INDEX "idx_silver_relation_ev_type" ON "silver"."relation_evidence" ("relation_type", "promoted");
