// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbingest

import (
	"time"
)

type IngestDiscoverCursor struct {
	ID            int64
	Source        string
	Keyword       string
	Watermark     string
	ExpectedTotal int64
	LastSeenTotal int64
	LastRunAt     *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type IngestDocDiscovery struct {
	ID            int64
	FetchDocID    int64
	Via           string
	Keyword       string
	SrcFetchDocID int64
	RelationType  string
	DiscoveredAt  time.Time
}

type IngestFetchArtifact struct {
	ID             int64
	FetchDocID     int64
	Kind           string
	RefKey         string
	FileKind       string
	FileName       string
	Url            *string
	UrlExpiresAt   *time.Time
	GatewayUrl     *string
	TargetSource   string
	TargetExtID    string
	IsOptional     bool
	State          string
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	Attempts       int32
	MaxAttempts    int32
	NextAttemptAt  *time.Time
	ContentHash    *string
	ResultRef      *string
	LastError      *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IngestFetchDoc struct {
	ID                   int64
	Source               string
	ExternalID           string
	State                string
	PlanReady            bool
	InScope              bool
	Provenance           string
	ArtifactsExpected    int32
	ArtifactsDone        int32
	ArtifactsFailed      int32
	TreeRecheckAfter     *time.Time
	TreeRecheckCount     int32
	ContentRecheckAfter  *time.Time
	ContentRecheckCount  int32
	ContentRecheckReason string
	ContentHash          *string
	DetailUrl            *string
	DiscoveredAt         time.Time
	UpdatedAt            time.Time
}
