// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbingest

import (
	"context"
)

type Querier interface {
	// Crash-safe lease: take up to claim_limit due body/tree/file artifacts for one
	// source. Includes lease-expired claimed rows so a crashed worker cannot wedge
	// the queue forever. Relation artifacts are intentionally left for the later
	// enrichment fetcher rather than being claimed by this drainer.
	ClaimArtifacts(ctx context.Context, arg ClaimArtifactsParams) ([]IngestFetchArtifact, error)
	ClearTreeRecheck(ctx context.Context, arg ClearTreeRecheckParams) error
	// Child work item, idempotent on (fetch_doc_id, kind, ref_key) so re-planning a
	// doc converges. Re-pointing url/gateway_url and resetting a non-terminal row to
	// pending lets a re-plan pick up moved URLs without losing terminal results.
	EnqueueArtifact(ctx context.Context, arg EnqueueArtifactParams) (int64, error)
	GetDiscoverCursor(ctx context.Context, arg GetDiscoverCursorParams) (IngestDiscoverCursor, error)
	GetFetchDoc(ctx context.Context, arg GetFetchDocParams) (IngestFetchDoc, error)
	// Resolve a claimed artifact's parent document (Fetch needs the source +
	// external_id + detail_url to fetch and to link bronze rows).
	GetFetchDocByID(ctx context.Context, id int64) (IngestFetchDoc, error)
	ListArtifactsByDoc(ctx context.Context, fetchDocID int64) ([]IngestFetchArtifact, error)
	// Paged ExtractAll helper: enumerate only the next completed, in-scope
	// fetch_doc IDs so the workflow never loads or schedules the whole corpus at
	// once.
	ListCompleteFetchDocIDsAfter(ctx context.Context, arg ListCompleteFetchDocIDsAfterParams) ([]int64, error)
	// Backfill/dev helper: enumerate completed fetch docs so Extract can be
	// triggered for already-fetched corpus rows without running Normalize/Index.
	ListCompleteFetchDocs(ctx context.Context, rowLimit int32) ([]IngestFetchDoc, error)
	// Docs with a due empty-tree re-check (bounded by tree_recheck_count in app logic).
	ListDocsNeedingTreeRecheck(ctx context.Context, arg ListDocsNeedingTreeRecheckParams) ([]IngestFetchDoc, error)
	// Live artifacts whose URL is about to expire — re-resolve before fetching.
	ListExpiringArtifacts(ctx context.Context, arg ListExpiringArtifactsParams) ([]IngestFetchArtifact, error)
	// Planned docs not yet complete — the work the completeness sweeper drives to done.
	ListIncompleteDocs(ctx context.Context, limit int32) ([]IngestFetchDoc, error)
	// Terminal success: record the content_hash + result_ref handle and clear the lease.
	MarkArtifactDone(ctx context.Context, arg MarkArtifactDoneParams) error
	// Retryable failure until attempts reach max_attempts, then dead-letter ('dead').
	// next_attempt_at schedules the backoff; the lease is cleared for re-claim.
	MarkArtifactError(ctx context.Context, arg MarkArtifactErrorParams) error
	// Terminal skip for an optional artifact that does not exist at the source; it
	// does not count against completeness.
	MarkArtifactSkipped(ctx context.Context, arg MarkArtifactSkippedParams) error
	// Compare-and-set completeness from child rows (never a lying flag): complete when
	// every non-optional artifact is terminal-good and none dead; partial when some
	// dead-lettered. Returns the resulting state so the caller can react.
	MarkDocCompleteIfDone(ctx context.Context, arg MarkDocCompleteIfDoneParams) (string, error)
	// Refresh an expiring presigned/gateway URL in place (g7 tokens, 24h S3 links)
	// and re-arm the artifact for fetching without losing its identity or attempts.
	ReResolveArtifactURL(ctx context.Context, arg ReResolveArtifactURLParams) error
	// Recompute the completeness counters from child rows — the single source of
	// truth. done = terminal-good (done/skipped/superseded); failed = dead.
	RecomputeDocCounters(ctx context.Context, arg RecomputeDocCountersParams) error
	// Append-only provenance: each (doc, keyword) hit and each relation edge that
	// surfaced the doc. '' sentinels keep the UNIQUE tuple total; re-recording is a
	// no-op so the ledger never loses (or duplicates) a reason a doc is in scope.
	RecordDocDiscovery(ctx context.Context, arg RecordDocDiscoveryParams) error
	// Re-open a completed document whose official body/file currently contains only
	// placeholder text. Body is due first so Fetch refreshes detail URLs before file
	// downloads are re-attempted. max_rechecks bounds eventually-missing source data.
	ScheduleSourceContentRecheck(ctx context.Context, arg ScheduleSourceContentRecheckParams) error
	ScheduleTreeRecheck(ctx context.Context, arg ScheduleTreeRecheckParams) error
	// Mark the doc's artifacts fully enumerated and snapshot the expected count, so
	// completeness becomes a compare against artifacts_done. Moves discovered/planning
	// into fetching.
	SetDocPlanReady(ctx context.Context, arg SetDocPlanReadyParams) error
	// An empty vbpl provision tree is often eventually-consistent. Mark the tree
	// artifact superseded (so it stops counting toward completeness) and schedule a
	// doc-level re-check; tree_recheck_count bounds the retries.
	SupersedeEmptyTree(ctx context.Context, arg SupersedeEmptyTreeParams) error
	// After a fresh detail fetch, retire stale file artifacts that the source no
	// longer advertises. This keeps refetch completeness from being blocked by
	// files that disappeared from the official detail response.
	SupersedeMissingFileArtifacts(ctx context.Context, arg SupersedeMissingFileArtifactsParams) error
	// Per-(source, keyword) watermark. expected_total snapshots data.total for the
	// slice; last_seen_total tracks drift so a slow keyword can't be silently skipped.
	UpsertDiscoverCursor(ctx context.Context, arg UpsertDiscoverCursorParams) error
	// Parent ledger row, idempotent on (source, external_id). Re-discovery converges
	// here. A changed discovery fingerprint re-opens the document so Fetch re-plans
	// the body/files; unchanged rows preserve their current fetch state.
	UpsertFetchDoc(ctx context.Context, arg UpsertFetchDocParams) (IngestFetchDoc, error)
}

var _ Querier = (*Queries)(nil)
