// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbingest

import (
	"context"
	"time"
)

const claimArtifacts = `-- name: ClaimArtifacts :many
UPDATE ingest.fetch_artifact
SET state = 'claimed',
    lease_owner = $1,
    lease_expires_at = $2,
    attempts = attempts + 1,
    updated_at = $3
WHERE id IN (
    SELECT a.id
    FROM ingest.fetch_artifact a
    JOIN ingest.fetch_doc d ON d.id = a.fetch_doc_id
    WHERE d.source = $4
      AND a.kind IN ('body', 'tree', 'file')
      AND NOT (a.kind = 'file' AND d.content_recheck_after IS NOT NULL)
      AND (
        (
          a.state IN ('pending', 'error')
          AND (a.next_attempt_at IS NULL OR a.next_attempt_at <= $3)
          AND (a.lease_expires_at IS NULL OR a.lease_expires_at <= $3)
        )
        OR (
          a.state = 'claimed'
          AND a.lease_expires_at IS NOT NULL
          AND a.lease_expires_at <= $3
        )
        OR (
          a.kind = 'tree'
          AND d.tree_recheck_after IS NOT NULL
          AND d.tree_recheck_after <= $3
          AND a.state IN ('skipped', 'superseded')
        )
      )
    -- Complete already-planned documents before planning more bodies. Without
    -- this, a capped run over a large discovery backlog can leave newly enqueued
    -- file artifacts behind hundreds of older body artifacts. A source-content
    -- recheck claims its body before files so detail URLs are fresh first.
    ORDER BY
      CASE
        WHEN a.kind = 'body' AND d.content_recheck_after IS NOT NULL THEN 0
        WHEN a.kind = 'tree' AND d.tree_recheck_after IS NOT NULL THEN 1
        WHEN a.kind = 'file' THEN 2
        WHEN a.kind = 'tree' THEN 3
        WHEN a.kind = 'body' THEN 4
        ELSE 5
      END,
      a.next_attempt_at NULLS FIRST,
      a.id
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
RETURNING id, fetch_doc_id, kind, ref_key, file_kind, file_name, url, url_expires_at, gateway_url, target_source, target_ext_id, is_optional, state, lease_owner, lease_expires_at, attempts, max_attempts, next_attempt_at, content_hash, result_ref, last_error, created_at, updated_at
`

type ClaimArtifactsParams struct {
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	Now            time.Time
	Source         string
	ClaimLimit     int32
}

// Crash-safe lease: take up to claim_limit due body/tree/file artifacts for one
// source. Includes lease-expired claimed rows so a crashed worker cannot wedge
// the queue forever. Relation artifacts are intentionally left for the later
// enrichment fetcher rather than being claimed by this drainer.
func (q *Queries) ClaimArtifacts(ctx context.Context, arg ClaimArtifactsParams) ([]IngestFetchArtifact, error) {
	rows, err := q.db.Query(ctx, claimArtifacts,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.Source,
		arg.ClaimLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchArtifact
	for rows.Next() {
		var i IngestFetchArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FetchDocID,
			&i.Kind,
			&i.RefKey,
			&i.FileKind,
			&i.FileName,
			&i.Url,
			&i.UrlExpiresAt,
			&i.GatewayUrl,
			&i.TargetSource,
			&i.TargetExtID,
			&i.IsOptional,
			&i.State,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.ContentHash,
			&i.ResultRef,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearTreeRecheck = `-- name: ClearTreeRecheck :exec
UPDATE ingest.fetch_doc
SET tree_recheck_after = NULL,
    updated_at = $2
WHERE id = $1
`

type ClearTreeRecheckParams struct {
	ID        int64
	UpdatedAt time.Time
}

func (q *Queries) ClearTreeRecheck(ctx context.Context, arg ClearTreeRecheckParams) error {
	_, err := q.db.Exec(ctx, clearTreeRecheck, arg.ID, arg.UpdatedAt)
	return err
}

const enqueueArtifact = `-- name: EnqueueArtifact :one
INSERT INTO ingest.fetch_artifact (
    fetch_doc_id, kind, ref_key, file_kind, file_name, url, url_expires_at, gateway_url,
    target_source, target_ext_id, is_optional, state, max_attempts,
    next_attempt_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'pending', $12, $13, $14, $14
)
ON CONFLICT (fetch_doc_id, kind, ref_key) DO UPDATE SET
    file_kind = EXCLUDED.file_kind,
    file_name = EXCLUDED.file_name,
    url = EXCLUDED.url,
    url_expires_at = EXCLUDED.url_expires_at,
    gateway_url = EXCLUDED.gateway_url,
    target_source = EXCLUDED.target_source,
    target_ext_id = EXCLUDED.target_ext_id,
    is_optional = EXCLUDED.is_optional,
    max_attempts = EXCLUDED.max_attempts,
    state = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN 'pending'
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
            THEN ingest.fetch_artifact.state
        ELSE 'pending'
    END,
    lease_owner = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND NOT EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN ingest.fetch_artifact.lease_owner
        ELSE NULL
    END,
    lease_expires_at = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND NOT EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN ingest.fetch_artifact.lease_expires_at
        ELSE NULL
    END,
    attempts = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN 0
        ELSE ingest.fetch_artifact.attempts
    END,
    next_attempt_at = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND NOT EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN ingest.fetch_artifact.next_attempt_at
        ELSE NULL
    END,
    content_hash = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN NULL
        ELSE ingest.fetch_artifact.content_hash
    END,
    result_ref = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN NULL
        ELSE ingest.fetch_artifact.result_ref
    END,
    last_error = CASE
        WHEN ingest.fetch_artifact.state IN ('done', 'skipped', 'superseded', 'dead')
         AND EXISTS (
            SELECT 1
            FROM ingest.fetch_doc d
            WHERE d.id = ingest.fetch_artifact.fetch_doc_id
              AND d.state = 'discovered'
              AND d.plan_ready = FALSE
         )
            THEN NULL
        ELSE ingest.fetch_artifact.last_error
    END,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type EnqueueArtifactParams struct {
	FetchDocID    int64
	Kind          string
	RefKey        string
	FileKind      string
	FileName      string
	Url           *string
	UrlExpiresAt  *time.Time
	GatewayUrl    *string
	TargetSource  string
	TargetExtID   string
	IsOptional    bool
	MaxAttempts   int32
	NextAttemptAt *time.Time
	CreatedAt     time.Time
}

// Child work item, idempotent on (fetch_doc_id, kind, ref_key) so re-planning a
// doc converges. Re-pointing url/gateway_url and resetting a non-terminal row to
// pending lets a re-plan pick up moved URLs without losing terminal results.
func (q *Queries) EnqueueArtifact(ctx context.Context, arg EnqueueArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueArtifact,
		arg.FetchDocID,
		arg.Kind,
		arg.RefKey,
		arg.FileKind,
		arg.FileName,
		arg.Url,
		arg.UrlExpiresAt,
		arg.GatewayUrl,
		arg.TargetSource,
		arg.TargetExtID,
		arg.IsOptional,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDiscoverCursor = `-- name: GetDiscoverCursor :one
SELECT id, source, keyword, watermark, expected_total, last_seen_total, last_run_at, created_at, updated_at FROM ingest.discover_cursor WHERE source = $1 AND keyword = $2
`

type GetDiscoverCursorParams struct {
	Source  string
	Keyword string
}

func (q *Queries) GetDiscoverCursor(ctx context.Context, arg GetDiscoverCursorParams) (IngestDiscoverCursor, error) {
	row := q.db.QueryRow(ctx, getDiscoverCursor, arg.Source, arg.Keyword)
	var i IngestDiscoverCursor
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Keyword,
		&i.Watermark,
		&i.ExpectedTotal,
		&i.LastSeenTotal,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFetchDoc = `-- name: GetFetchDoc :one
SELECT id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at FROM ingest.fetch_doc WHERE source = $1 AND external_id = $2
`

type GetFetchDocParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) GetFetchDoc(ctx context.Context, arg GetFetchDocParams) (IngestFetchDoc, error) {
	row := q.db.QueryRow(ctx, getFetchDoc, arg.Source, arg.ExternalID)
	var i IngestFetchDoc
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.State,
		&i.PlanReady,
		&i.InScope,
		&i.Provenance,
		&i.ArtifactsExpected,
		&i.ArtifactsDone,
		&i.ArtifactsFailed,
		&i.TreeRecheckAfter,
		&i.TreeRecheckCount,
		&i.ContentRecheckAfter,
		&i.ContentRecheckCount,
		&i.ContentRecheckReason,
		&i.ContentHash,
		&i.DetailUrl,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFetchDocByID = `-- name: GetFetchDocByID :one
SELECT id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at FROM ingest.fetch_doc WHERE id = $1
`

// Resolve a claimed artifact's parent document (Fetch needs the source +
// external_id + detail_url to fetch and to link bronze rows).
func (q *Queries) GetFetchDocByID(ctx context.Context, id int64) (IngestFetchDoc, error) {
	row := q.db.QueryRow(ctx, getFetchDocByID, id)
	var i IngestFetchDoc
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.State,
		&i.PlanReady,
		&i.InScope,
		&i.Provenance,
		&i.ArtifactsExpected,
		&i.ArtifactsDone,
		&i.ArtifactsFailed,
		&i.TreeRecheckAfter,
		&i.TreeRecheckCount,
		&i.ContentRecheckAfter,
		&i.ContentRecheckCount,
		&i.ContentRecheckReason,
		&i.ContentHash,
		&i.DetailUrl,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsByDoc = `-- name: ListArtifactsByDoc :many
SELECT id, fetch_doc_id, kind, ref_key, file_kind, file_name, url, url_expires_at, gateway_url, target_source, target_ext_id, is_optional, state, lease_owner, lease_expires_at, attempts, max_attempts, next_attempt_at, content_hash, result_ref, last_error, created_at, updated_at FROM ingest.fetch_artifact
WHERE fetch_doc_id = $1
ORDER BY kind, ref_key
`

func (q *Queries) ListArtifactsByDoc(ctx context.Context, fetchDocID int64) ([]IngestFetchArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByDoc, fetchDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchArtifact
	for rows.Next() {
		var i IngestFetchArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FetchDocID,
			&i.Kind,
			&i.RefKey,
			&i.FileKind,
			&i.FileName,
			&i.Url,
			&i.UrlExpiresAt,
			&i.GatewayUrl,
			&i.TargetSource,
			&i.TargetExtID,
			&i.IsOptional,
			&i.State,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.ContentHash,
			&i.ResultRef,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompleteFetchDocIDsAfter = `-- name: ListCompleteFetchDocIDsAfter :many
SELECT id FROM ingest.fetch_doc
WHERE state = 'complete'
  AND in_scope
  AND id > $1
ORDER BY id
LIMIT $2
`

type ListCompleteFetchDocIDsAfterParams struct {
	AfterID  int64
	RowLimit int32
}

// Paged ExtractAll helper: enumerate only the next completed, in-scope
// fetch_doc IDs so the workflow never loads or schedules the whole corpus at
// once.
func (q *Queries) ListCompleteFetchDocIDsAfter(ctx context.Context, arg ListCompleteFetchDocIDsAfterParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCompleteFetchDocIDsAfter, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompleteFetchDocs = `-- name: ListCompleteFetchDocs :many
SELECT id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at FROM ingest.fetch_doc
WHERE state = 'complete'
  AND in_scope
ORDER BY id
LIMIT $1
`

// Backfill/dev helper: enumerate completed fetch docs so Extract can be
// triggered for already-fetched corpus rows without running Normalize/Index.
func (q *Queries) ListCompleteFetchDocs(ctx context.Context, rowLimit int32) ([]IngestFetchDoc, error) {
	rows, err := q.db.Query(ctx, listCompleteFetchDocs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchDoc
	for rows.Next() {
		var i IngestFetchDoc
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.State,
			&i.PlanReady,
			&i.InScope,
			&i.Provenance,
			&i.ArtifactsExpected,
			&i.ArtifactsDone,
			&i.ArtifactsFailed,
			&i.TreeRecheckAfter,
			&i.TreeRecheckCount,
			&i.ContentRecheckAfter,
			&i.ContentRecheckCount,
			&i.ContentRecheckReason,
			&i.ContentHash,
			&i.DetailUrl,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsNeedingTreeRecheck = `-- name: ListDocsNeedingTreeRecheck :many
SELECT id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at FROM ingest.fetch_doc
WHERE tree_recheck_after IS NOT NULL AND tree_recheck_after <= $1
ORDER BY tree_recheck_after
LIMIT $2
`

type ListDocsNeedingTreeRecheckParams struct {
	TreeRecheckAfter *time.Time
	Limit            int32
}

// Docs with a due empty-tree re-check (bounded by tree_recheck_count in app logic).
func (q *Queries) ListDocsNeedingTreeRecheck(ctx context.Context, arg ListDocsNeedingTreeRecheckParams) ([]IngestFetchDoc, error) {
	rows, err := q.db.Query(ctx, listDocsNeedingTreeRecheck, arg.TreeRecheckAfter, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchDoc
	for rows.Next() {
		var i IngestFetchDoc
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.State,
			&i.PlanReady,
			&i.InScope,
			&i.Provenance,
			&i.ArtifactsExpected,
			&i.ArtifactsDone,
			&i.ArtifactsFailed,
			&i.TreeRecheckAfter,
			&i.TreeRecheckCount,
			&i.ContentRecheckAfter,
			&i.ContentRecheckCount,
			&i.ContentRecheckReason,
			&i.ContentHash,
			&i.DetailUrl,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringArtifacts = `-- name: ListExpiringArtifacts :many
SELECT id, fetch_doc_id, kind, ref_key, file_kind, file_name, url, url_expires_at, gateway_url, target_source, target_ext_id, is_optional, state, lease_owner, lease_expires_at, attempts, max_attempts, next_attempt_at, content_hash, result_ref, last_error, created_at, updated_at FROM ingest.fetch_artifact
WHERE state IN ('pending', 'error')
  AND url_expires_at IS NOT NULL
  AND url_expires_at <= $1
ORDER BY url_expires_at
LIMIT $2
`

type ListExpiringArtifactsParams struct {
	UrlExpiresAt *time.Time
	Limit        int32
}

// Live artifacts whose URL is about to expire — re-resolve before fetching.
func (q *Queries) ListExpiringArtifacts(ctx context.Context, arg ListExpiringArtifactsParams) ([]IngestFetchArtifact, error) {
	rows, err := q.db.Query(ctx, listExpiringArtifacts, arg.UrlExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchArtifact
	for rows.Next() {
		var i IngestFetchArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FetchDocID,
			&i.Kind,
			&i.RefKey,
			&i.FileKind,
			&i.FileName,
			&i.Url,
			&i.UrlExpiresAt,
			&i.GatewayUrl,
			&i.TargetSource,
			&i.TargetExtID,
			&i.IsOptional,
			&i.State,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.ContentHash,
			&i.ResultRef,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteDocs = `-- name: ListIncompleteDocs :many
SELECT id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at FROM ingest.fetch_doc
WHERE plan_ready AND state NOT IN ('complete', 'error')
ORDER BY updated_at
LIMIT $1
`

// Planned docs not yet complete — the work the completeness sweeper drives to done.
func (q *Queries) ListIncompleteDocs(ctx context.Context, limit int32) ([]IngestFetchDoc, error) {
	rows, err := q.db.Query(ctx, listIncompleteDocs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFetchDoc
	for rows.Next() {
		var i IngestFetchDoc
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.State,
			&i.PlanReady,
			&i.InScope,
			&i.Provenance,
			&i.ArtifactsExpected,
			&i.ArtifactsDone,
			&i.ArtifactsFailed,
			&i.TreeRecheckAfter,
			&i.TreeRecheckCount,
			&i.ContentRecheckAfter,
			&i.ContentRecheckCount,
			&i.ContentRecheckReason,
			&i.ContentHash,
			&i.DetailUrl,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactDone = `-- name: MarkArtifactDone :exec
UPDATE ingest.fetch_artifact
SET state = 'done',
    content_hash = $2,
    result_ref = $3,
    last_error = NULL,
    lease_owner = NULL,
    lease_expires_at = NULL,
    next_attempt_at = NULL,
    updated_at = $4
WHERE id = $1
`

type MarkArtifactDoneParams struct {
	ID          int64
	ContentHash *string
	ResultRef   *string
	UpdatedAt   time.Time
}

// Terminal success: record the content_hash + result_ref handle and clear the lease.
func (q *Queries) MarkArtifactDone(ctx context.Context, arg MarkArtifactDoneParams) error {
	_, err := q.db.Exec(ctx, markArtifactDone,
		arg.ID,
		arg.ContentHash,
		arg.ResultRef,
		arg.UpdatedAt,
	)
	return err
}

const markArtifactError = `-- name: MarkArtifactError :exec
UPDATE ingest.fetch_artifact
SET state = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'error' END,
    last_error = $2,
    next_attempt_at = $3,
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $4
WHERE id = $1
`

type MarkArtifactErrorParams struct {
	ID            int64
	LastError     *string
	NextAttemptAt *time.Time
	UpdatedAt     time.Time
}

// Retryable failure until attempts reach max_attempts, then dead-letter ('dead').
// next_attempt_at schedules the backoff; the lease is cleared for re-claim.
func (q *Queries) MarkArtifactError(ctx context.Context, arg MarkArtifactErrorParams) error {
	_, err := q.db.Exec(ctx, markArtifactError,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.UpdatedAt,
	)
	return err
}

const markArtifactSkipped = `-- name: MarkArtifactSkipped :exec
UPDATE ingest.fetch_artifact
SET state = 'skipped',
    last_error = NULL,
    lease_owner = NULL,
    lease_expires_at = NULL,
    next_attempt_at = NULL,
    updated_at = $2
WHERE id = $1
`

type MarkArtifactSkippedParams struct {
	ID        int64
	UpdatedAt time.Time
}

// Terminal skip for an optional artifact that does not exist at the source; it
// does not count against completeness.
func (q *Queries) MarkArtifactSkipped(ctx context.Context, arg MarkArtifactSkippedParams) error {
	_, err := q.db.Exec(ctx, markArtifactSkipped, arg.ID, arg.UpdatedAt)
	return err
}

const markDocCompleteIfDone = `-- name: MarkDocCompleteIfDone :one
UPDATE ingest.fetch_doc d
SET state = CASE
        WHEN agg.dead > 0 THEN 'partial'
        WHEN agg.total > 0 AND agg.pending = 0 THEN 'complete'
        ELSE d.state
    END,
    artifacts_done = agg.good,
    artifacts_failed = agg.dead,
    updated_at = $1
FROM (
    SELECT
        COUNT(*) FILTER (WHERE NOT is_optional) AS total,
        COUNT(*) FILTER (WHERE NOT is_optional AND state IN ('done', 'skipped', 'superseded')) AS good,
        COUNT(*) FILTER (WHERE NOT is_optional AND state = 'dead') AS dead,
        COUNT(*) FILTER (WHERE NOT is_optional AND state IN ('pending', 'claimed', 'error')) AS pending
    FROM ingest.fetch_artifact
    WHERE fetch_doc_id = $2
) agg
WHERE d.id = $2 AND d.plan_ready
RETURNING d.state
`

type MarkDocCompleteIfDoneParams struct {
	Now        time.Time
	FetchDocID int64
}

// Compare-and-set completeness from child rows (never a lying flag): complete when
// every non-optional artifact is terminal-good and none dead; partial when some
// dead-lettered. Returns the resulting state so the caller can react.
func (q *Queries) MarkDocCompleteIfDone(ctx context.Context, arg MarkDocCompleteIfDoneParams) (string, error) {
	row := q.db.QueryRow(ctx, markDocCompleteIfDone, arg.Now, arg.FetchDocID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const reResolveArtifactURL = `-- name: ReResolveArtifactURL :exec
UPDATE ingest.fetch_artifact
SET url = $2,
    url_expires_at = $3,
    gateway_url = $4,
    state = CASE WHEN state IN ('dead', 'done', 'skipped', 'superseded') THEN state ELSE 'pending' END,
    updated_at = $5
WHERE id = $1
`

type ReResolveArtifactURLParams struct {
	ID           int64
	Url          *string
	UrlExpiresAt *time.Time
	GatewayUrl   *string
	UpdatedAt    time.Time
}

// Refresh an expiring presigned/gateway URL in place (g7 tokens, 24h S3 links)
// and re-arm the artifact for fetching without losing its identity or attempts.
func (q *Queries) ReResolveArtifactURL(ctx context.Context, arg ReResolveArtifactURLParams) error {
	_, err := q.db.Exec(ctx, reResolveArtifactURL,
		arg.ID,
		arg.Url,
		arg.UrlExpiresAt,
		arg.GatewayUrl,
		arg.UpdatedAt,
	)
	return err
}

const recomputeDocCounters = `-- name: RecomputeDocCounters :exec
UPDATE ingest.fetch_doc d
SET artifacts_done = c.done,
    artifacts_failed = c.failed,
    updated_at = $2
FROM (
    SELECT
        fetch_doc_id,
        COUNT(*) FILTER (WHERE NOT is_optional AND state IN ('done', 'skipped', 'superseded')) AS done,
        COUNT(*) FILTER (WHERE NOT is_optional AND state = 'dead') AS failed
    FROM ingest.fetch_artifact
    WHERE fetch_doc_id = $1
    GROUP BY fetch_doc_id
) c
WHERE d.id = $1 AND c.fetch_doc_id = d.id
`

type RecomputeDocCountersParams struct {
	ID        int64
	UpdatedAt time.Time
}

// Recompute the completeness counters from child rows — the single source of
// truth. done = terminal-good (done/skipped/superseded); failed = dead.
func (q *Queries) RecomputeDocCounters(ctx context.Context, arg RecomputeDocCountersParams) error {
	_, err := q.db.Exec(ctx, recomputeDocCounters, arg.ID, arg.UpdatedAt)
	return err
}

const recordDocDiscovery = `-- name: RecordDocDiscovery :exec
INSERT INTO ingest.doc_discovery (
    fetch_doc_id, via, keyword, src_fetch_doc_id, relation_type, discovered_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (fetch_doc_id, via, keyword, src_fetch_doc_id, relation_type) DO NOTHING
`

type RecordDocDiscoveryParams struct {
	FetchDocID    int64
	Via           string
	Keyword       string
	SrcFetchDocID int64
	RelationType  string
	DiscoveredAt  time.Time
}

// Append-only provenance: each (doc, keyword) hit and each relation edge that
// surfaced the doc. ” sentinels keep the UNIQUE tuple total; re-recording is a
// no-op so the ledger never loses (or duplicates) a reason a doc is in scope.
func (q *Queries) RecordDocDiscovery(ctx context.Context, arg RecordDocDiscoveryParams) error {
	_, err := q.db.Exec(ctx, recordDocDiscovery,
		arg.FetchDocID,
		arg.Via,
		arg.Keyword,
		arg.SrcFetchDocID,
		arg.RelationType,
		arg.DiscoveredAt,
	)
	return err
}

const scheduleSourceContentRecheck = `-- name: ScheduleSourceContentRecheck :exec
WITH bumped AS (
    UPDATE ingest.fetch_doc d
    SET state = 'discovered',
        plan_ready = FALSE,
        artifacts_expected = 0,
        artifacts_done = 0,
        artifacts_failed = 0,
        content_recheck_after = $1,
        content_recheck_count = d.content_recheck_count + 1,
        content_recheck_reason = $3,
        updated_at = $4
    WHERE d.id = $5
      AND d.content_recheck_count < $6
      AND NOT (d.state = 'discovered' AND d.plan_ready = FALSE AND d.content_recheck_after IS NOT NULL)
    RETURNING d.id
)
UPDATE ingest.fetch_artifact a
SET state = 'pending',
    lease_owner = NULL,
    lease_expires_at = NULL,
    attempts = 0,
    next_attempt_at = CASE
        WHEN a.kind = 'body' THEN $1
        ELSE $2
    END,
    last_error = $3,
    updated_at = $4
FROM bumped
WHERE a.fetch_doc_id = bumped.id
  AND a.kind IN ('body', 'file')
`

type ScheduleSourceContentRecheckParams struct {
	BodyNextAttemptAt *time.Time
	FileNextAttemptAt *time.Time
	Reason            *string
	UpdatedAt         time.Time
	FetchDocID        int64
	MaxRechecks       int32
}

// Re-open a completed document whose official body/file currently contains only
// placeholder text. Body is due first so Fetch refreshes detail URLs before file
// downloads are re-attempted. max_rechecks bounds eventually-missing source data.
func (q *Queries) ScheduleSourceContentRecheck(ctx context.Context, arg ScheduleSourceContentRecheckParams) error {
	_, err := q.db.Exec(ctx, scheduleSourceContentRecheck,
		arg.BodyNextAttemptAt,
		arg.FileNextAttemptAt,
		arg.Reason,
		arg.UpdatedAt,
		arg.FetchDocID,
		arg.MaxRechecks,
	)
	return err
}

const scheduleTreeRecheck = `-- name: ScheduleTreeRecheck :exec
UPDATE ingest.fetch_doc
SET tree_recheck_after = $2,
    tree_recheck_count = tree_recheck_count + 1,
    updated_at = $3
WHERE id = $1
`

type ScheduleTreeRecheckParams struct {
	ID               int64
	TreeRecheckAfter *time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ScheduleTreeRecheck(ctx context.Context, arg ScheduleTreeRecheckParams) error {
	_, err := q.db.Exec(ctx, scheduleTreeRecheck, arg.ID, arg.TreeRecheckAfter, arg.UpdatedAt)
	return err
}

const setDocPlanReady = `-- name: SetDocPlanReady :exec
UPDATE ingest.fetch_doc
SET plan_ready = TRUE,
    artifacts_expected = $2,
    state = CASE WHEN state IN ('discovered', 'planning') THEN 'fetching' ELSE state END,
    content_recheck_after = NULL,
    updated_at = $3
WHERE id = $1
`

type SetDocPlanReadyParams struct {
	ID                int64
	ArtifactsExpected int32
	UpdatedAt         time.Time
}

// Mark the doc's artifacts fully enumerated and snapshot the expected count, so
// completeness becomes a compare against artifacts_done. Moves discovered/planning
// into fetching.
func (q *Queries) SetDocPlanReady(ctx context.Context, arg SetDocPlanReadyParams) error {
	_, err := q.db.Exec(ctx, setDocPlanReady, arg.ID, arg.ArtifactsExpected, arg.UpdatedAt)
	return err
}

const supersedeEmptyTree = `-- name: SupersedeEmptyTree :exec
UPDATE ingest.fetch_artifact
SET state = 'superseded',
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $2
WHERE fetch_doc_id = $1 AND kind = 'tree'
`

type SupersedeEmptyTreeParams struct {
	FetchDocID int64
	UpdatedAt  time.Time
}

// An empty vbpl provision tree is often eventually-consistent. Mark the tree
// artifact superseded (so it stops counting toward completeness) and schedule a
// doc-level re-check; tree_recheck_count bounds the retries.
func (q *Queries) SupersedeEmptyTree(ctx context.Context, arg SupersedeEmptyTreeParams) error {
	_, err := q.db.Exec(ctx, supersedeEmptyTree, arg.FetchDocID, arg.UpdatedAt)
	return err
}

const supersedeMissingFileArtifacts = `-- name: SupersedeMissingFileArtifacts :exec
UPDATE ingest.fetch_artifact
SET state = 'superseded',
    lease_owner = NULL,
    lease_expires_at = NULL,
    next_attempt_at = NULL,
    updated_at = $1
WHERE fetch_doc_id = $2
  AND kind = 'file'
  AND NOT (ref_key = ANY($3::text[]))
`

type SupersedeMissingFileArtifactsParams struct {
	UpdatedAt     time.Time
	FetchDocID    int64
	ActiveRefKeys []string
}

// After a fresh detail fetch, retire stale file artifacts that the source no
// longer advertises. This keeps refetch completeness from being blocked by
// files that disappeared from the official detail response.
func (q *Queries) SupersedeMissingFileArtifacts(ctx context.Context, arg SupersedeMissingFileArtifactsParams) error {
	_, err := q.db.Exec(ctx, supersedeMissingFileArtifacts, arg.UpdatedAt, arg.FetchDocID, arg.ActiveRefKeys)
	return err
}

const upsertDiscoverCursor = `-- name: UpsertDiscoverCursor :exec
INSERT INTO ingest.discover_cursor (
    source, keyword, watermark, expected_total, last_seen_total, last_run_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
ON CONFLICT (source, keyword) DO UPDATE SET
    watermark = EXCLUDED.watermark,
    expected_total = EXCLUDED.expected_total,
    last_seen_total = EXCLUDED.last_seen_total,
    last_run_at = EXCLUDED.last_run_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertDiscoverCursorParams struct {
	Source        string
	Keyword       string
	Watermark     string
	ExpectedTotal int64
	LastSeenTotal int64
	LastRunAt     *time.Time
	CreatedAt     time.Time
}

// Per-(source, keyword) watermark. expected_total snapshots data.total for the
// slice; last_seen_total tracks drift so a slow keyword can't be silently skipped.
func (q *Queries) UpsertDiscoverCursor(ctx context.Context, arg UpsertDiscoverCursorParams) error {
	_, err := q.db.Exec(ctx, upsertDiscoverCursor,
		arg.Source,
		arg.Keyword,
		arg.Watermark,
		arg.ExpectedTotal,
		arg.LastSeenTotal,
		arg.LastRunAt,
		arg.CreatedAt,
	)
	return err
}

const upsertFetchDoc = `-- name: UpsertFetchDoc :one
INSERT INTO ingest.fetch_doc (
    source, external_id, state, in_scope, provenance, content_hash, detail_url,
    discovered_at, updated_at
) VALUES (
    $1, $2, COALESCE($8, 'discovered'), $3, $4, $5, $6, $7, $7
)
ON CONFLICT (source, external_id) DO UPDATE SET
    in_scope = ingest.fetch_doc.in_scope OR EXCLUDED.in_scope,
    provenance = CASE
        WHEN ingest.fetch_doc.provenance = '' THEN EXCLUDED.provenance
        WHEN ingest.fetch_doc.provenance = 'relation' AND EXCLUDED.provenance <> 'relation'
            THEN EXCLUDED.provenance
        ELSE ingest.fetch_doc.provenance
    END,
    state = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN COALESCE($8, 'discovered')
        ELSE ingest.fetch_doc.state
    END,
    plan_ready = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN FALSE
        ELSE ingest.fetch_doc.plan_ready
    END,
    artifacts_expected = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN 0
        ELSE ingest.fetch_doc.artifacts_expected
    END,
    artifacts_done = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN 0
        ELSE ingest.fetch_doc.artifacts_done
    END,
    artifacts_failed = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN 0
        ELSE ingest.fetch_doc.artifacts_failed
    END,
    tree_recheck_after = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN NULL
        ELSE ingest.fetch_doc.tree_recheck_after
    END,
    tree_recheck_count = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN 0
        ELSE ingest.fetch_doc.tree_recheck_count
    END,
    content_recheck_after = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN NULL
        ELSE ingest.fetch_doc.content_recheck_after
    END,
    content_recheck_count = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN 0
        ELSE ingest.fetch_doc.content_recheck_count
    END,
    content_recheck_reason = CASE
        WHEN EXCLUDED.content_hash IS NOT NULL
         AND ingest.fetch_doc.content_hash IS DISTINCT FROM EXCLUDED.content_hash
            THEN ''
        ELSE ingest.fetch_doc.content_recheck_reason
    END,
    content_hash = COALESCE(EXCLUDED.content_hash, ingest.fetch_doc.content_hash),
    detail_url = COALESCE(EXCLUDED.detail_url, ingest.fetch_doc.detail_url),
    updated_at = EXCLUDED.updated_at
RETURNING id, source, external_id, state, plan_ready, in_scope, provenance, artifacts_expected, artifacts_done, artifacts_failed, tree_recheck_after, tree_recheck_count, content_recheck_after, content_recheck_count, content_recheck_reason, content_hash, detail_url, discovered_at, updated_at
`

type UpsertFetchDocParams struct {
	Source       string
	ExternalID   string
	InScope      bool
	Provenance   string
	ContentHash  *string
	DetailUrl    *string
	DiscoveredAt time.Time
	State        interface{}
}

// Parent ledger row, idempotent on (source, external_id). Re-discovery converges
// here. A changed discovery fingerprint re-opens the document so Fetch re-plans
// the body/files; unchanged rows preserve their current fetch state.
func (q *Queries) UpsertFetchDoc(ctx context.Context, arg UpsertFetchDocParams) (IngestFetchDoc, error) {
	row := q.db.QueryRow(ctx, upsertFetchDoc,
		arg.Source,
		arg.ExternalID,
		arg.InScope,
		arg.Provenance,
		arg.ContentHash,
		arg.DetailUrl,
		arg.DiscoveredAt,
		arg.State,
	)
	var i IngestFetchDoc
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.State,
		&i.PlanReady,
		&i.InScope,
		&i.Provenance,
		&i.ArtifactsExpected,
		&i.ArtifactsDone,
		&i.ArtifactsFailed,
		&i.TreeRecheckAfter,
		&i.TreeRecheckCount,
		&i.ContentRecheckAfter,
		&i.ContentRecheckCount,
		&i.ContentRecheckReason,
		&i.ContentHash,
		&i.DetailUrl,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}
