// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbbronze

import (
	"encoding/json"
	"time"
)

type BronzeRawFile struct {
	ID               int64
	SourceDocumentID int64
	FileKind         string
	FileFormat       string
	IsAuthoritative  bool
	Ordinal          int32
	Label            string
	Lang             string
	Url              *string
	StoragePath      *string
	Sha256           *string
	ByteSize         *int64
	ContentHash      *string
	CollectedAt      time.Time
	FirstCollectedAt time.Time
}

type BronzeRawPayload struct {
	ID               int64
	SourceDocumentID int64
	Kind             string
	Content          *string
	ContentHash      *string
	CollectedAt      time.Time
	FirstCollectedAt time.Time
}

type BronzeSourceDocument struct {
	ID               int64
	Source           string
	ExternalID       string
	DocGuid          string
	DocNumber        *string
	DocNumberNorm    string
	DocType          *string
	DocTypeCode      string
	Issuer           *string
	IssuerCode       string
	Title            *string
	IssuedAt         *time.Time
	EffectiveAt      *time.Time
	ExpireAt         *time.Time
	StatusRaw        *string
	GazetteNumber    string
	GazetteDate      *time.Time
	HasContent       bool
	IsConsolidated   bool
	DetailUrl        *string
	ContentHash      *string
	RawMeta          json.RawMessage
	DiscoveredAt     time.Time
	FetchedAt        *time.Time
	CollectedAt      time.Time
	FirstCollectedAt time.Time
}
