// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbbronze

import (
	"context"
	"encoding/json"
	"time"
)

const deleteRawPayloadByKind = `-- name: DeleteRawPayloadByKind :exec
DELETE FROM bronze.raw_payload
WHERE source_document_id = $1 AND kind = $2
`

type DeleteRawPayloadByKindParams struct {
	SourceDocumentID int64
	Kind             string
}

func (q *Queries) DeleteRawPayloadByKind(ctx context.Context, arg DeleteRawPayloadByKindParams) error {
	_, err := q.db.Exec(ctx, deleteRawPayloadByKind, arg.SourceDocumentID, arg.Kind)
	return err
}

const enrichSourceDocument = `-- name: EnrichSourceDocument :exec
UPDATE bronze.source_document
SET doc_guid = $3,
    doc_number_norm = $4,
    doc_type_code = $5,
    issuer_code = $6,
    expire_at = $7,
    gazette_number = $8,
    gazette_date = $9,
    has_content = $10,
    is_consolidated = $11,
    collected_at = $12
WHERE source = $1 AND external_id = $2
`

type EnrichSourceDocumentParams struct {
	Source         string
	ExternalID     string
	DocGuid        string
	DocNumberNorm  string
	DocTypeCode    string
	IssuerCode     string
	ExpireAt       *time.Time
	GazetteNumber  string
	GazetteDate    *time.Time
	HasContent     bool
	IsConsolidated bool
	CollectedAt    time.Time
}

// Fetch-stage enrichment of the resilient-dedup and gazette columns, keyed by the
// natural key. Kept separate from UpsertSourceDocument so the discovery harness
// stays simple while Fetch fills doc_guid / *_norm / *_code / gazette / flags.
func (q *Queries) EnrichSourceDocument(ctx context.Context, arg EnrichSourceDocumentParams) error {
	_, err := q.db.Exec(ctx, enrichSourceDocument,
		arg.Source,
		arg.ExternalID,
		arg.DocGuid,
		arg.DocNumberNorm,
		arg.DocTypeCode,
		arg.IssuerCode,
		arg.ExpireAt,
		arg.GazetteNumber,
		arg.GazetteDate,
		arg.HasContent,
		arg.IsConsolidated,
		arg.CollectedAt,
	)
	return err
}

const listRawFilesByDocument = `-- name: ListRawFilesByDocument :many
SELECT id, source_document_id, file_kind, file_format, is_authoritative, ordinal, label, lang, url, storage_path, sha256, byte_size, content_hash, collected_at, first_collected_at FROM bronze.raw_file
WHERE source_document_id = $1
ORDER BY
    CASE file_kind
        WHEN 'main' THEN 0
        WHEN 'appendix' THEN 1
        WHEN 'attachment' THEN 2
        WHEN 'version_snapshot' THEN 3
        WHEN 'original_scan' THEN 4
        ELSE 9
    END,
    ordinal,
    file_format
`

func (q *Queries) ListRawFilesByDocument(ctx context.Context, sourceDocumentID int64) ([]BronzeRawFile, error) {
	rows, err := q.db.Query(ctx, listRawFilesByDocument, sourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BronzeRawFile
	for rows.Next() {
		var i BronzeRawFile
		if err := rows.Scan(
			&i.ID,
			&i.SourceDocumentID,
			&i.FileKind,
			&i.FileFormat,
			&i.IsAuthoritative,
			&i.Ordinal,
			&i.Label,
			&i.Lang,
			&i.Url,
			&i.StoragePath,
			&i.Sha256,
			&i.ByteSize,
			&i.ContentHash,
			&i.CollectedAt,
			&i.FirstCollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawPayloadsByDocument = `-- name: ListRawPayloadsByDocument :many
SELECT id, source_document_id, kind, content, content_hash, collected_at, first_collected_at FROM bronze.raw_payload
WHERE source_document_id = $1
ORDER BY kind
`

func (q *Queries) ListRawPayloadsByDocument(ctx context.Context, sourceDocumentID int64) ([]BronzeRawPayload, error) {
	rows, err := q.db.Query(ctx, listRawPayloadsByDocument, sourceDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BronzeRawPayload
	for rows.Next() {
		var i BronzeRawPayload
		if err := rows.Scan(
			&i.ID,
			&i.SourceDocumentID,
			&i.Kind,
			&i.Content,
			&i.ContentHash,
			&i.CollectedAt,
			&i.FirstCollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceDocumentsBySource = `-- name: ListSourceDocumentsBySource :many
SELECT id, source, external_id, doc_guid, doc_number, doc_number_norm, doc_type, doc_type_code, issuer, issuer_code, title, issued_at, effective_at, expire_at, status_raw, gazette_number, gazette_date, has_content, is_consolidated, detail_url, content_hash, raw_meta, discovered_at, fetched_at, collected_at, first_collected_at FROM bronze.source_document
WHERE source = $1
ORDER BY issued_at DESC NULLS LAST, id DESC
LIMIT $2 OFFSET $3
`

type ListSourceDocumentsBySourceParams struct {
	Source string
	Limit  int32
	Offset int32
}

func (q *Queries) ListSourceDocumentsBySource(ctx context.Context, arg ListSourceDocumentsBySourceParams) ([]BronzeSourceDocument, error) {
	rows, err := q.db.Query(ctx, listSourceDocumentsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BronzeSourceDocument
	for rows.Next() {
		var i BronzeSourceDocument
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.DocGuid,
			&i.DocNumber,
			&i.DocNumberNorm,
			&i.DocType,
			&i.DocTypeCode,
			&i.Issuer,
			&i.IssuerCode,
			&i.Title,
			&i.IssuedAt,
			&i.EffectiveAt,
			&i.ExpireAt,
			&i.StatusRaw,
			&i.GazetteNumber,
			&i.GazetteDate,
			&i.HasContent,
			&i.IsConsolidated,
			&i.DetailUrl,
			&i.ContentHash,
			&i.RawMeta,
			&i.DiscoveredAt,
			&i.FetchedAt,
			&i.CollectedAt,
			&i.FirstCollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceDocumentByExternalID = `-- name: SourceDocumentByExternalID :one
SELECT id, source, external_id, doc_guid, doc_number, doc_number_norm, doc_type, doc_type_code, issuer, issuer_code, title, issued_at, effective_at, expire_at, status_raw, gazette_number, gazette_date, has_content, is_consolidated, detail_url, content_hash, raw_meta, discovered_at, fetched_at, collected_at, first_collected_at FROM bronze.source_document
WHERE source = $1 AND external_id = $2
`

type SourceDocumentByExternalIDParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) SourceDocumentByExternalID(ctx context.Context, arg SourceDocumentByExternalIDParams) (BronzeSourceDocument, error) {
	row := q.db.QueryRow(ctx, sourceDocumentByExternalID, arg.Source, arg.ExternalID)
	var i BronzeSourceDocument
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.DocGuid,
		&i.DocNumber,
		&i.DocNumberNorm,
		&i.DocType,
		&i.DocTypeCode,
		&i.Issuer,
		&i.IssuerCode,
		&i.Title,
		&i.IssuedAt,
		&i.EffectiveAt,
		&i.ExpireAt,
		&i.StatusRaw,
		&i.GazetteNumber,
		&i.GazetteDate,
		&i.HasContent,
		&i.IsConsolidated,
		&i.DetailUrl,
		&i.ContentHash,
		&i.RawMeta,
		&i.DiscoveredAt,
		&i.FetchedAt,
		&i.CollectedAt,
		&i.FirstCollectedAt,
	)
	return i, err
}

const sourceDocumentByID = `-- name: SourceDocumentByID :one
SELECT id, source, external_id, doc_guid, doc_number, doc_number_norm, doc_type, doc_type_code, issuer, issuer_code, title, issued_at, effective_at, expire_at, status_raw, gazette_number, gazette_date, has_content, is_consolidated, detail_url, content_hash, raw_meta, discovered_at, fetched_at, collected_at, first_collected_at FROM bronze.source_document WHERE id = $1
`

func (q *Queries) SourceDocumentByID(ctx context.Context, id int64) (BronzeSourceDocument, error) {
	row := q.db.QueryRow(ctx, sourceDocumentByID, id)
	var i BronzeSourceDocument
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.DocGuid,
		&i.DocNumber,
		&i.DocNumberNorm,
		&i.DocType,
		&i.DocTypeCode,
		&i.Issuer,
		&i.IssuerCode,
		&i.Title,
		&i.IssuedAt,
		&i.EffectiveAt,
		&i.ExpireAt,
		&i.StatusRaw,
		&i.GazetteNumber,
		&i.GazetteDate,
		&i.HasContent,
		&i.IsConsolidated,
		&i.DetailUrl,
		&i.ContentHash,
		&i.RawMeta,
		&i.DiscoveredAt,
		&i.FetchedAt,
		&i.CollectedAt,
		&i.FirstCollectedAt,
	)
	return i, err
}

const sourceDocumentContentHash = `-- name: SourceDocumentContentHash :one
SELECT content_hash FROM bronze.source_document
WHERE source = $1 AND external_id = $2
`

type SourceDocumentContentHashParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) SourceDocumentContentHash(ctx context.Context, arg SourceDocumentContentHashParams) (*string, error) {
	row := q.db.QueryRow(ctx, sourceDocumentContentHash, arg.Source, arg.ExternalID)
	var content_hash *string
	err := row.Scan(&content_hash)
	return content_hash, err
}

const updateRawFileLabel = `-- name: UpdateRawFileLabel :exec
UPDATE bronze.raw_file
SET label = $5
WHERE source_document_id = $1
  AND file_kind = $2
  AND ordinal = $3
  AND file_format = $4
  AND label IS DISTINCT FROM $5
`

type UpdateRawFileLabelParams struct {
	SourceDocumentID int64
	FileKind         string
	Ordinal          int32
	FileFormat       string
	Label            string
}

// Source detail re-planning may learn a better source-provided filename after a
// file was already downloaded. Update the display label by the same natural key
// used by UpsertRawFile; local storage remains hash-addressed.
func (q *Queries) UpdateRawFileLabel(ctx context.Context, arg UpdateRawFileLabelParams) error {
	_, err := q.db.Exec(ctx, updateRawFileLabel,
		arg.SourceDocumentID,
		arg.FileKind,
		arg.Ordinal,
		arg.FileFormat,
		arg.Label,
	)
	return err
}

const upsertRawFile = `-- name: UpsertRawFile :one
INSERT INTO bronze.raw_file (
    source_document_id, file_kind, file_format, is_authoritative, ordinal,
    label, lang, url, storage_path, sha256, byte_size, content_hash,
    collected_at, first_collected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13
)
ON CONFLICT (source_document_id, file_kind, ordinal, file_format) DO UPDATE SET
    is_authoritative = EXCLUDED.is_authoritative,
    label = EXCLUDED.label,
    lang = EXCLUDED.lang,
    url = EXCLUDED.url,
    storage_path = EXCLUDED.storage_path,
    sha256 = EXCLUDED.sha256,
    byte_size = EXCLUDED.byte_size,
    content_hash = EXCLUDED.content_hash,
    collected_at = EXCLUDED.collected_at
RETURNING id
`

type UpsertRawFileParams struct {
	SourceDocumentID int64
	FileKind         string
	FileFormat       string
	IsAuthoritative  bool
	Ordinal          int32
	Label            string
	Lang             string
	Url              *string
	StoragePath      *string
	Sha256           *string
	ByteSize         *int64
	ContentHash      *string
	CollectedAt      time.Time
}

// Idempotent on the (source_document_id, file_kind, ordinal, file_format) natural
// key so re-downloading the same role+format file converges instead of duping.
func (q *Queries) UpsertRawFile(ctx context.Context, arg UpsertRawFileParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRawFile,
		arg.SourceDocumentID,
		arg.FileKind,
		arg.FileFormat,
		arg.IsAuthoritative,
		arg.Ordinal,
		arg.Label,
		arg.Lang,
		arg.Url,
		arg.StoragePath,
		arg.Sha256,
		arg.ByteSize,
		arg.ContentHash,
		arg.CollectedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertRawPayload = `-- name: UpsertRawPayload :one
INSERT INTO bronze.raw_payload (
    source_document_id, kind, content, content_hash, collected_at, first_collected_at
) VALUES (
    $1, $2, $3, $4, $5, $5
)
ON CONFLICT (source_document_id, kind) DO UPDATE SET
    content = EXCLUDED.content,
    content_hash = EXCLUDED.content_hash,
    collected_at = EXCLUDED.collected_at
RETURNING id
`

type UpsertRawPayloadParams struct {
	SourceDocumentID int64
	Kind             string
	Content          *string
	ContentHash      *string
	CollectedAt      time.Time
}

// Idempotent on (source_document_id, kind): a re-fetch overwrites the single body,
// tree, references, or detail blob for the document instead of duplicating it.
func (q *Queries) UpsertRawPayload(ctx context.Context, arg UpsertRawPayloadParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRawPayload,
		arg.SourceDocumentID,
		arg.Kind,
		arg.Content,
		arg.ContentHash,
		arg.CollectedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceDocument = `-- name: UpsertSourceDocument :one
INSERT INTO bronze.source_document (
    source, external_id, doc_number, title, doc_type, issuer,
    issued_at, effective_at, status_raw, detail_url, content_hash,
    raw_meta, discovered_at, fetched_at, collected_at, first_collected_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, COALESCE($14, $13::timestamptz), COALESCE($14, $13::timestamptz)
)
ON CONFLICT (source, external_id) DO UPDATE SET
    doc_number = COALESCE(EXCLUDED.doc_number, source_document.doc_number),
    title = COALESCE(EXCLUDED.title, source_document.title),
    doc_type = COALESCE(EXCLUDED.doc_type, source_document.doc_type),
    issuer = COALESCE(EXCLUDED.issuer, source_document.issuer),
    issued_at = COALESCE(EXCLUDED.issued_at, source_document.issued_at),
    effective_at = COALESCE(EXCLUDED.effective_at, source_document.effective_at),
    status_raw = COALESCE(EXCLUDED.status_raw, source_document.status_raw),
    detail_url = COALESCE(EXCLUDED.detail_url, source_document.detail_url),
    content_hash = COALESCE(EXCLUDED.content_hash, source_document.content_hash),
    -- raw_meta and fetched_at are phase-specific: Discover supplies raw_meta with a
    -- NULL fetched_at; Fetch supplies fetched_at. COALESCE so neither phase (nor an
    -- incremental re-discovery, which carries a NULL fetched_at) clobbers the other.
    raw_meta = COALESCE(EXCLUDED.raw_meta, source_document.raw_meta),
    fetched_at = COALESCE(EXCLUDED.fetched_at, source_document.fetched_at),
    collected_at = COALESCE(EXCLUDED.fetched_at, EXCLUDED.discovered_at)
RETURNING id
`

type UpsertSourceDocumentParams struct {
	Source       string
	ExternalID   string
	DocNumber    *string
	Title        *string
	DocType      *string
	Issuer       *string
	IssuedAt     *time.Time
	EffectiveAt  *time.Time
	StatusRaw    *string
	DetailUrl    *string
	ContentHash  *string
	RawMeta      json.RawMessage
	DiscoveredAt time.Time
	FetchedAt    *time.Time
}

// Idempotent on the (source, external_id) natural key so Discover/Fetch retries
// converge. Returns the row id used as the business key from silver. The
// discovery harness supplies the core columns + raw_meta (the full source record);
// the resilient-dedup columns (doc_guid, *_norm, *_code, gazette*, flags) default
// empty until Fetch enriches them. collected_at/first_collected_at anchor the
// content_hash change-log.
func (q *Queries) UpsertSourceDocument(ctx context.Context, arg UpsertSourceDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSourceDocument,
		arg.Source,
		arg.ExternalID,
		arg.DocNumber,
		arg.Title,
		arg.DocType,
		arg.Issuer,
		arg.IssuedAt,
		arg.EffectiveAt,
		arg.StatusRaw,
		arg.DetailUrl,
		arg.ContentHash,
		arg.RawMeta,
		arg.DiscoveredAt,
		arg.FetchedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
