// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbbronze

import (
	"context"
)

type Querier interface {
	DeleteRawPayloadByKind(ctx context.Context, arg DeleteRawPayloadByKindParams) error
	// Fetch-stage enrichment of the resilient-dedup and gazette columns, keyed by the
	// natural key. Kept separate from UpsertSourceDocument so the discovery harness
	// stays simple while Fetch fills doc_guid / *_norm / *_code / gazette / flags.
	EnrichSourceDocument(ctx context.Context, arg EnrichSourceDocumentParams) error
	ListRawFilesByDocument(ctx context.Context, sourceDocumentID int64) ([]BronzeRawFile, error)
	ListRawPayloadsByDocument(ctx context.Context, sourceDocumentID int64) ([]BronzeRawPayload, error)
	ListSourceDocumentsBySource(ctx context.Context, arg ListSourceDocumentsBySourceParams) ([]BronzeSourceDocument, error)
	SourceDocumentByExternalID(ctx context.Context, arg SourceDocumentByExternalIDParams) (BronzeSourceDocument, error)
	SourceDocumentByID(ctx context.Context, id int64) (BronzeSourceDocument, error)
	SourceDocumentContentHash(ctx context.Context, arg SourceDocumentContentHashParams) (*string, error)
	// Source detail re-planning may learn a better source-provided filename after a
	// file was already downloaded. Update the display label by the same natural key
	// used by UpsertRawFile; local storage remains hash-addressed.
	UpdateRawFileLabel(ctx context.Context, arg UpdateRawFileLabelParams) error
	// Idempotent on the (source_document_id, file_kind, ordinal, file_format) natural
	// key so re-downloading the same role+format file converges instead of duping.
	UpsertRawFile(ctx context.Context, arg UpsertRawFileParams) (int64, error)
	// Idempotent on (source_document_id, kind): a re-fetch overwrites the single body,
	// tree, references, or detail blob for the document instead of duplicating it.
	UpsertRawPayload(ctx context.Context, arg UpsertRawPayloadParams) (int64, error)
	// Idempotent on the (source, external_id) natural key so Discover/Fetch retries
	// converge. Returns the row id used as the business key from silver. The
	// discovery harness supplies the core columns + raw_meta (the full source record);
	// the resilient-dedup columns (doc_guid, *_norm, *_code, gazette*, flags) default
	// empty until Fetch enriches them. collected_at/first_collected_at anchor the
	// content_hash change-log.
	UpsertSourceDocument(ctx context.Context, arg UpsertSourceDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
