// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbconfig

import (
	"time"
)

type ConfigDiscoveryKeyword struct {
	ID        int64
	Term      string
	Source    string
	Origin    string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigIssuerCode struct {
	ID        int64
	Source    string
	Code      string
	Name      string
	InScope   bool
	IsSbv     bool
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigRelationType struct {
	ID         int64
	Source     string
	Code       string
	Label      string
	IsAmending bool
	Origin     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ConfigScopeTerm struct {
	ID           int64
	Jurisdiction string
	Term         string
	TermClass    string
	Theme        string
	Origin       string
	Enabled      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ConfigSetting struct {
	ID        int64
	Key       string
	Value     string
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigValidityStatus struct {
	ID           int64
	Source       string
	Code         string
	StatusClass  string
	IsCurrentLaw bool
	Origin       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
