// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbconfig

import (
	"context"
)

const deleteSeedDiscoveryKeywords = `-- name: DeleteSeedDiscoveryKeywords :exec
DELETE FROM config.discovery_keyword WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedDiscoveryKeywords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedDiscoveryKeywords)
	return err
}

const deleteSeedIssuerCodes = `-- name: DeleteSeedIssuerCodes :exec
DELETE FROM config.issuer_code WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedIssuerCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedIssuerCodes)
	return err
}

const deleteSeedRelationTypes = `-- name: DeleteSeedRelationTypes :exec
DELETE FROM config.relation_type WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedRelationTypes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedRelationTypes)
	return err
}

const deleteSeedScopeTerms = `-- name: DeleteSeedScopeTerms :exec

DELETE FROM config.scope_term WHERE origin = 'seed'
`

// Seed queries (cmd/seed). Each re-seed deletes the managed ('seed') rows and
// re-inserts from the CSV; ON CONFLICT DO NOTHING means a user override sharing a
// natural key is preserved. origin='user' rows are never deleted.
func (q *Queries) DeleteSeedScopeTerms(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedScopeTerms)
	return err
}

const deleteSeedSettings = `-- name: DeleteSeedSettings :exec
DELETE FROM config.setting WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedSettings)
	return err
}

const deleteSeedValidityStatuses = `-- name: DeleteSeedValidityStatuses :exec
DELETE FROM config.validity_status WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedValidityStatuses(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedValidityStatuses)
	return err
}

const insertSeedDiscoveryKeyword = `-- name: InsertSeedDiscoveryKeyword :exec
INSERT INTO config.discovery_keyword (term, source, origin)
VALUES ($1, $2, 'seed') ON CONFLICT (source, term) DO NOTHING
`

type InsertSeedDiscoveryKeywordParams struct {
	Term   string
	Source string
}

func (q *Queries) InsertSeedDiscoveryKeyword(ctx context.Context, arg InsertSeedDiscoveryKeywordParams) error {
	_, err := q.db.Exec(ctx, insertSeedDiscoveryKeyword, arg.Term, arg.Source)
	return err
}

const insertSeedIssuerCode = `-- name: InsertSeedIssuerCode :exec
INSERT INTO config.issuer_code (source, code, name, in_scope, is_sbv, origin)
VALUES ($1, $2, $3, $4, $5, 'seed') ON CONFLICT (source, code) DO NOTHING
`

type InsertSeedIssuerCodeParams struct {
	Source  string
	Code    string
	Name    string
	InScope bool
	IsSbv   bool
}

func (q *Queries) InsertSeedIssuerCode(ctx context.Context, arg InsertSeedIssuerCodeParams) error {
	_, err := q.db.Exec(ctx, insertSeedIssuerCode,
		arg.Source,
		arg.Code,
		arg.Name,
		arg.InScope,
		arg.IsSbv,
	)
	return err
}

const insertSeedRelationType = `-- name: InsertSeedRelationType :exec
INSERT INTO config.relation_type (source, code, label, is_amending, origin)
VALUES ($1, $2, $3, $4, 'seed') ON CONFLICT (source, code) DO NOTHING
`

type InsertSeedRelationTypeParams struct {
	Source     string
	Code       string
	Label      string
	IsAmending bool
}

func (q *Queries) InsertSeedRelationType(ctx context.Context, arg InsertSeedRelationTypeParams) error {
	_, err := q.db.Exec(ctx, insertSeedRelationType,
		arg.Source,
		arg.Code,
		arg.Label,
		arg.IsAmending,
	)
	return err
}

const insertSeedScopeTerm = `-- name: InsertSeedScopeTerm :exec
INSERT INTO config.scope_term (jurisdiction, term, term_class, theme, origin)
VALUES ($1, $2, $3, $4, 'seed') ON CONFLICT (jurisdiction, term_class, term) DO NOTHING
`

type InsertSeedScopeTermParams struct {
	Jurisdiction string
	Term         string
	TermClass    string
	Theme        string
}

func (q *Queries) InsertSeedScopeTerm(ctx context.Context, arg InsertSeedScopeTermParams) error {
	_, err := q.db.Exec(ctx, insertSeedScopeTerm,
		arg.Jurisdiction,
		arg.Term,
		arg.TermClass,
		arg.Theme,
	)
	return err
}

const insertSeedSetting = `-- name: InsertSeedSetting :exec
INSERT INTO config.setting (key, value, origin)
VALUES ($1, $2, 'seed') ON CONFLICT (key) DO NOTHING
`

type InsertSeedSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) InsertSeedSetting(ctx context.Context, arg InsertSeedSettingParams) error {
	_, err := q.db.Exec(ctx, insertSeedSetting, arg.Key, arg.Value)
	return err
}

const insertSeedValidityStatus = `-- name: InsertSeedValidityStatus :exec
INSERT INTO config.validity_status (source, code, status_class, is_current_law, origin)
VALUES ($1, $2, $3, $4, 'seed') ON CONFLICT (source, code) DO NOTHING
`

type InsertSeedValidityStatusParams struct {
	Source       string
	Code         string
	StatusClass  string
	IsCurrentLaw bool
}

func (q *Queries) InsertSeedValidityStatus(ctx context.Context, arg InsertSeedValidityStatusParams) error {
	_, err := q.db.Exec(ctx, insertSeedValidityStatus,
		arg.Source,
		arg.Code,
		arg.StatusClass,
		arg.IsCurrentLaw,
	)
	return err
}

const listDiscoveryKeywords = `-- name: ListDiscoveryKeywords :many
SELECT term FROM config.discovery_keyword
WHERE enabled AND source IN ($1, '') ORDER BY term
`

// Keywords for a source plus the source-agnostic ones (”).
func (q *Queries) ListDiscoveryKeywords(ctx context.Context, source string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDiscoveryKeywords, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var term string
		if err := rows.Scan(&term); err != nil {
			return nil, err
		}
		items = append(items, term)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuerCodes = `-- name: ListIssuerCodes :many
SELECT source, code, name, in_scope, is_sbv FROM config.issuer_code ORDER BY source, code
`

type ListIssuerCodesRow struct {
	Source  string
	Code    string
	Name    string
	InScope bool
	IsSbv   bool
}

func (q *Queries) ListIssuerCodes(ctx context.Context) ([]ListIssuerCodesRow, error) {
	rows, err := q.db.Query(ctx, listIssuerCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuerCodesRow
	for rows.Next() {
		var i ListIssuerCodesRow
		if err := rows.Scan(
			&i.Source,
			&i.Code,
			&i.Name,
			&i.InScope,
			&i.IsSbv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationTypes = `-- name: ListRelationTypes :many
SELECT source, code, label, is_amending FROM config.relation_type ORDER BY source, code
`

type ListRelationTypesRow struct {
	Source     string
	Code       string
	Label      string
	IsAmending bool
}

func (q *Queries) ListRelationTypes(ctx context.Context) ([]ListRelationTypesRow, error) {
	rows, err := q.db.Query(ctx, listRelationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationTypesRow
	for rows.Next() {
		var i ListRelationTypesRow
		if err := rows.Scan(
			&i.Source,
			&i.Code,
			&i.Label,
			&i.IsAmending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeTerms = `-- name: ListScopeTerms :many

SELECT term, term_class FROM config.scope_term WHERE enabled AND jurisdiction = $1 ORDER BY term_class, term
`

type ListScopeTermsRow struct {
	Term      string
	TermClass string
}

// Load queries (read config into the app at startup).
func (q *Queries) ListScopeTerms(ctx context.Context, jurisdiction string) ([]ListScopeTermsRow, error) {
	rows, err := q.db.Query(ctx, listScopeTerms, jurisdiction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScopeTermsRow
	for rows.Next() {
		var i ListScopeTermsRow
		if err := rows.Scan(&i.Term, &i.TermClass); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM config.setting
`

type ListSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidityStatuses = `-- name: ListValidityStatuses :many
SELECT source, code, status_class, is_current_law FROM config.validity_status ORDER BY source, code
`

type ListValidityStatusesRow struct {
	Source       string
	Code         string
	StatusClass  string
	IsCurrentLaw bool
}

func (q *Queries) ListValidityStatuses(ctx context.Context) ([]ListValidityStatusesRow, error) {
	rows, err := q.db.Query(ctx, listValidityStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListValidityStatusesRow
	for rows.Next() {
		var i ListValidityStatusesRow
		if err := rows.Scan(
			&i.Source,
			&i.Code,
			&i.StatusClass,
			&i.IsCurrentLaw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sbvAgencyIDs = `-- name: SbvAgencyIDs :many
SELECT code FROM config.issuer_code WHERE source = $1 AND is_sbv ORDER BY code
`

func (q *Queries) SbvAgencyIDs(ctx context.Context, source string) ([]string, error) {
	rows, err := q.db.Query(ctx, sbvAgencyIDs, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
