// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbconfig

import (
	"context"
)

type Querier interface {
	DeleteSeedDiscoveryKeywords(ctx context.Context) error
	DeleteSeedIssuerCodes(ctx context.Context) error
	DeleteSeedRelationTypes(ctx context.Context) error
	// Seed queries (cmd/seed). Each re-seed deletes the managed ('seed') rows and
	// re-inserts from the CSV; ON CONFLICT DO NOTHING means a user override sharing a
	// natural key is preserved. origin='user' rows are never deleted.
	DeleteSeedScopeTerms(ctx context.Context) error
	DeleteSeedSettings(ctx context.Context) error
	DeleteSeedValidityStatuses(ctx context.Context) error
	InsertSeedDiscoveryKeyword(ctx context.Context, arg InsertSeedDiscoveryKeywordParams) error
	InsertSeedIssuerCode(ctx context.Context, arg InsertSeedIssuerCodeParams) error
	InsertSeedRelationType(ctx context.Context, arg InsertSeedRelationTypeParams) error
	InsertSeedScopeTerm(ctx context.Context, arg InsertSeedScopeTermParams) error
	InsertSeedSetting(ctx context.Context, arg InsertSeedSettingParams) error
	InsertSeedValidityStatus(ctx context.Context, arg InsertSeedValidityStatusParams) error
	// Keywords for a source plus the source-agnostic ones ('').
	ListDiscoveryKeywords(ctx context.Context, source string) ([]string, error)
	ListIssuerCodes(ctx context.Context) ([]ListIssuerCodesRow, error)
	ListRelationTypes(ctx context.Context) ([]ListRelationTypesRow, error)
	// Load queries (read config into the app at startup).
	ListScopeTerms(ctx context.Context, jurisdiction string) ([]ListScopeTermsRow, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListValidityStatuses(ctx context.Context) ([]ListValidityStatusesRow, error)
	SbvAgencyIDs(ctx context.Context, source string) ([]string, error)
}

var _ Querier = (*Queries)(nil)
