// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsilver

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SilverAmendmentEvent struct {
	ID               int64
	ActingDocumentID int64
	TargetRefID      int64
	ChangeOp         string
	EffectiveDate    *time.Time
	Source           *string
}

type SilverDocRef struct {
	ID         int64
	RefKey     string
	DocumentID *int64
	Label      *string
	SrcRef     json.RawMessage
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type SilverDocument struct {
	ID               int64
	DocKey           string
	DocNumber        *string
	DocNumberNorm    string
	Title            *string
	DocType          *string
	DocTypeCode      string
	Issuer           *string
	IssuerCode       string
	IssuedAt         *time.Time
	Signer           *string
	IsConsolidated   bool
	Markdown         *string
	SourceDocumentID *int64
	IndexClass       string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SilverDocumentAlias struct {
	ID          int64
	Source      string
	ExternalID  string
	DocumentID  int64
	MatchMethod string
	Confidence  pgtype.Float8
}

type SilverDocumentGazette struct {
	ID               int64
	DocumentID       int64
	GazetteNumber    string
	GazetteDate      *time.Time
	SourceDocumentID *int64
}

type SilverDocumentRelation struct {
	ID              int64
	FromDocumentID  int64
	ToRefID         int64
	RelationType    string
	RelationTypeRaw *int32
	FromSectionID   *int64
	ToCitation      *string
	Source          *string
}

type SilverDocumentSection struct {
	ID           int64
	DocumentID   int64
	ParentID     *int64
	NodeKey      *string
	Ptype        pgtype.Int2
	Kind         string
	Ordinal      int32
	Label        *string
	Heading      *string
	CitationPath string
	Content      *string
}

type SilverDocumentText struct {
	ID                int64
	DocumentID        int64
	Authority         string
	Source            string
	RawFileID         *int64
	Markdown          *string
	SourceFileSha256  *string
	VerbatimSha256    *string
	IsBinding         bool
	ExtractEngine     *string
	ExtractConfidence pgtype.Float8
	NeedsReview       bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SilverDocumentTopic struct {
	ID             int64
	DocumentID     int64
	Topic          string
	TopicSource    string
	MatchedKeyword *string
	Confidence     pgtype.Float8
}

type SilverRelationEvidence struct {
	ID              int64
	FromDocumentID  int64
	FromSectionID   *int64
	TargetRefID     int64
	EvidenceKey     string
	EvidenceKind    string
	RelationType    string
	RelationTypeRaw *int32
	Operator        string
	TargetText      string
	TargetCitation  *string
	Citation        string
	Snippet         string
	Source          string
	SourceAuthority string
	Confidence      float64
	Promoted        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SilverValidityPeriod struct {
	ID            int64
	DocumentID    int64
	SectionID     *int64
	VersionID     *int64
	StatusCode    string
	StatusClass   string
	EffFrom       *time.Time
	EffTo         *time.Time
	Reason        *string
	CausedByRefID *int64
	Source        *string
	ObservedAt    time.Time
	SupersededAt  *time.Time
}
