// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsilver

import (
	"context"
)

type Querier interface {
	// Bitemporal point query: the validity in legal effect on @as_of that the system
	// believed at observation time (not superseded). eff_from/eff_to open ends are
	// treated as unbounded so an open-ended in-force record still matches.
	CurrentValidityAsOf(ctx context.Context, arg CurrentValidityAsOfParams) (SilverValidityPeriod, error)
	// The latest non-superseded document-level validity record — the status the
	// in-force pre-filter reads in MVP1.
	CurrentValidityByDocument(ctx context.Context, documentID int64) (SilverValidityPeriod, error)
	DeleteDocumentRelationsByDocument(ctx context.Context, fromDocumentID int64) error
	DeleteDocumentRelationsByDocumentSource(ctx context.Context, arg DeleteDocumentRelationsByDocumentSourceParams) error
	DeleteRelationEvidenceByDocument(ctx context.Context, fromDocumentID int64) error
	DeleteRelationEvidenceByDocumentSource(ctx context.Context, arg DeleteRelationEvidenceByDocumentSourceParams) error
	// Normalize replaces the parsed provision tree on each run. ON DELETE CASCADE
	// removes child sections under this document's roots.
	DeleteSectionsByDocument(ctx context.Context, documentID int64) (int64, error)
	DocRefByKey(ctx context.Context, refKey string) (SilverDocRef, error)
	DocumentByID(ctx context.Context, id int64) (SilverDocument, error)
	DocumentByKey(ctx context.Context, docKey string) (SilverDocument, error)
	DocumentIDByAlias(ctx context.Context, arg DocumentIDByAliasParams) (int64, error)
	// Every document carrying a normalized số ký hiệu. More than one row means the
	// bare number is ambiguous (distinct documents share it) and a number-only
	// reference must not resolve.
	DocumentIDsByNumberNorm(ctx context.Context, docNumberNorm string) ([]int64, error)
	// Return the highest-authority binding text for a document (used by Normalize).
	GetBindingText(ctx context.Context, documentID int64) (SilverDocumentText, error)
	InsertAmendmentEvent(ctx context.Context, arg InsertAmendmentEventParams) (int64, error)
	InsertValidityPeriod(ctx context.Context, arg InsertValidityPeriodParams) (int64, error)
	ListAmendmentsTargeting(ctx context.Context, targetRefID int64) ([]SilverAmendmentEvent, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]SilverDocument, error)
	ListGazettesByDocument(ctx context.Context, documentID int64) ([]SilverDocumentGazette, error)
	ListRelationEvidenceByDocument(ctx context.Context, fromDocumentID int64) ([]SilverRelationEvidence, error)
	ListRelationEvidenceTo(ctx context.Context, targetRefID int64) ([]SilverRelationEvidence, error)
	ListRelationsFrom(ctx context.Context, fromDocumentID int64) ([]SilverDocumentRelation, error)
	ListRelationsTo(ctx context.Context, toRefID int64) ([]SilverDocumentRelation, error)
	ListSectionsByDocument(ctx context.Context, documentID int64) ([]ListSectionsByDocumentRow, error)
	// Texts for a document, best authority first; retrieval restricts binding answers
	// to is_binding rows.
	ListTextsByDocument(ctx context.Context, documentID int64) ([]SilverDocumentText, error)
	ListTopicsByDocument(ctx context.Context, documentID int64) ([]SilverDocumentTopic, error)
	// The out-of-corpus reference targets not yet ingested (the partial-index sweep).
	ListUnresolvedStubs(ctx context.Context, limit int32) ([]SilverDocRef, error)
	// Link a stub to a now-ingested document. Run when a new document lands: every ref
	// whose ref_key matches the new doc resolves with no rewrites to the edges that
	// already point at it.
	ResolveDocRef(ctx context.Context, arg ResolveDocRefParams) error
	// Link a number-keyed reference stub to a document, but only while exactly one
	// document carries that normalized number. A bare số ký hiệu cannot pick
	// between documents that share it (e.g. a Luật and a Nghị quyết numbered
	// 51/2005/QH11), so ambiguous references stay stubs.
	ResolveDocRefForUniqueNumber(ctx context.Context, arg ResolveDocRefForUniqueNumberParams) error
	// Records the Index-stage scope verdict ('primary' | 'relation_context').
	SetDocumentIndexClass(ctx context.Context, arg SetDocumentIndexClassParams) error
	SupersedeValidityPeriods(ctx context.Context, arg SupersedeValidityPeriodsParams) error
	// Idempotent on ref_key. Creating a reference target is safe whether or not the
	// target is ingested yet: document_id stays NULL (a stub) until ResolveDocRef
	// links it. COALESCE keeps an already-resolved ref from regressing to a stub.
	UpsertDocRef(ctx context.Context, arg UpsertDocRefParams) (int64, error)
	// Idempotent on the canonical doc_key so dedup re-runs converge on one logical doc.
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error)
	// Maps a source's (source, external_id) to the merged document; idempotent so the
	// cross-source identity map can be rebuilt safely. match_method + confidence make
	// the merge auditable.
	UpsertDocumentAlias(ctx context.Context, arg UpsertDocumentAliasParams) (int64, error)
	// Idempotent on (document_id, gazette_number); a doc may appear in many issues.
	UpsertDocumentGazette(ctx context.Context, arg UpsertDocumentGazetteParams) (int64, error)
	// Idempotent on (from_document_id, to_ref_id, relation_type) so the ingested
	// reference graph converges. The target is a doc_ref (resolved or stub).
	UpsertDocumentRelation(ctx context.Context, arg UpsertDocumentRelationParams) (int64, error)
	// Idempotent on (document_id, authority, source) so re-extraction with the same
	// engine/source converges instead of stacking text rows.
	UpsertDocumentText(ctx context.Context, arg UpsertDocumentTextParams) (int64, error)
	UpsertDocumentTopic(ctx context.Context, arg UpsertDocumentTopicParams) error
	UpsertRelationEvidence(ctx context.Context, arg UpsertRelationEvidenceParams) (int64, error)
	// Idempotent on (document_id, citation_path) so re-parsing the provision tree
	// converges. parent_id is resolved by the caller before insert.
	UpsertSection(ctx context.Context, arg UpsertSectionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
