// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbsilver

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentValidityAsOf = `-- name: CurrentValidityAsOf :one
SELECT id, document_id, section_id, version_id, status_code, status_class, eff_from, eff_to, reason, caused_by_ref_id, source, observed_at, superseded_at FROM silver.validity_period
WHERE document_id = $1
  AND section_id IS NULL
  AND superseded_at IS NULL
  AND (eff_from IS NULL OR eff_from <= $2)
  AND (eff_to IS NULL OR eff_to > $2)
ORDER BY observed_at DESC
LIMIT 1
`

type CurrentValidityAsOfParams struct {
	DocumentID int64
	AsOf       *time.Time
}

// Bitemporal point query: the validity in legal effect on @as_of that the system
// believed at observation time (not superseded). eff_from/eff_to open ends are
// treated as unbounded so an open-ended in-force record still matches.
func (q *Queries) CurrentValidityAsOf(ctx context.Context, arg CurrentValidityAsOfParams) (SilverValidityPeriod, error) {
	row := q.db.QueryRow(ctx, currentValidityAsOf, arg.DocumentID, arg.AsOf)
	var i SilverValidityPeriod
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SectionID,
		&i.VersionID,
		&i.StatusCode,
		&i.StatusClass,
		&i.EffFrom,
		&i.EffTo,
		&i.Reason,
		&i.CausedByRefID,
		&i.Source,
		&i.ObservedAt,
		&i.SupersededAt,
	)
	return i, err
}

const currentValidityByDocument = `-- name: CurrentValidityByDocument :one
SELECT id, document_id, section_id, version_id, status_code, status_class, eff_from, eff_to, reason, caused_by_ref_id, source, observed_at, superseded_at FROM silver.validity_period
WHERE document_id = $1 AND section_id IS NULL AND superseded_at IS NULL
ORDER BY observed_at DESC
LIMIT 1
`

// The latest non-superseded document-level validity record — the status the
// in-force pre-filter reads in MVP1.
func (q *Queries) CurrentValidityByDocument(ctx context.Context, documentID int64) (SilverValidityPeriod, error) {
	row := q.db.QueryRow(ctx, currentValidityByDocument, documentID)
	var i SilverValidityPeriod
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.SectionID,
		&i.VersionID,
		&i.StatusCode,
		&i.StatusClass,
		&i.EffFrom,
		&i.EffTo,
		&i.Reason,
		&i.CausedByRefID,
		&i.Source,
		&i.ObservedAt,
		&i.SupersededAt,
	)
	return i, err
}

const deleteDocumentRelationsByDocument = `-- name: DeleteDocumentRelationsByDocument :exec
DELETE FROM silver.document_relation
WHERE from_document_id = $1
`

func (q *Queries) DeleteDocumentRelationsByDocument(ctx context.Context, fromDocumentID int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentRelationsByDocument, fromDocumentID)
	return err
}

const deleteDocumentRelationsByDocumentSource = `-- name: DeleteDocumentRelationsByDocumentSource :exec
DELETE FROM silver.document_relation
WHERE from_document_id = $1
  AND source = $2
`

type DeleteDocumentRelationsByDocumentSourceParams struct {
	FromDocumentID int64
	Source         *string
}

func (q *Queries) DeleteDocumentRelationsByDocumentSource(ctx context.Context, arg DeleteDocumentRelationsByDocumentSourceParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentRelationsByDocumentSource, arg.FromDocumentID, arg.Source)
	return err
}

const deleteRelationEvidenceByDocument = `-- name: DeleteRelationEvidenceByDocument :exec
DELETE FROM silver.relation_evidence
WHERE from_document_id = $1
`

func (q *Queries) DeleteRelationEvidenceByDocument(ctx context.Context, fromDocumentID int64) error {
	_, err := q.db.Exec(ctx, deleteRelationEvidenceByDocument, fromDocumentID)
	return err
}

const deleteRelationEvidenceByDocumentSource = `-- name: DeleteRelationEvidenceByDocumentSource :exec
DELETE FROM silver.relation_evidence
WHERE from_document_id = $1
  AND source = $2
`

type DeleteRelationEvidenceByDocumentSourceParams struct {
	FromDocumentID int64
	Source         string
}

func (q *Queries) DeleteRelationEvidenceByDocumentSource(ctx context.Context, arg DeleteRelationEvidenceByDocumentSourceParams) error {
	_, err := q.db.Exec(ctx, deleteRelationEvidenceByDocumentSource, arg.FromDocumentID, arg.Source)
	return err
}

const deleteSectionsByDocument = `-- name: DeleteSectionsByDocument :execrows
DELETE FROM silver.document_section
WHERE document_id = $1
`

// Normalize replaces the parsed provision tree on each run. ON DELETE CASCADE
// removes child sections under this document's roots.
func (q *Queries) DeleteSectionsByDocument(ctx context.Context, documentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSectionsByDocument, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const docRefByKey = `-- name: DocRefByKey :one
SELECT id, ref_key, document_id, label, src_ref, created_at, updated_at FROM silver.doc_ref WHERE ref_key = $1
`

func (q *Queries) DocRefByKey(ctx context.Context, refKey string) (SilverDocRef, error) {
	row := q.db.QueryRow(ctx, docRefByKey, refKey)
	var i SilverDocRef
	err := row.Scan(
		&i.ID,
		&i.RefKey,
		&i.DocumentID,
		&i.Label,
		&i.SrcRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const documentByID = `-- name: DocumentByID :one
SELECT id, doc_key, doc_number, doc_number_norm, title, doc_type, doc_type_code, issuer, issuer_code, issued_at, signer, is_consolidated, markdown, source_document_id, index_class, created_at, updated_at FROM silver.document WHERE id = $1
`

func (q *Queries) DocumentByID(ctx context.Context, id int64) (SilverDocument, error) {
	row := q.db.QueryRow(ctx, documentByID, id)
	var i SilverDocument
	err := row.Scan(
		&i.ID,
		&i.DocKey,
		&i.DocNumber,
		&i.DocNumberNorm,
		&i.Title,
		&i.DocType,
		&i.DocTypeCode,
		&i.Issuer,
		&i.IssuerCode,
		&i.IssuedAt,
		&i.Signer,
		&i.IsConsolidated,
		&i.Markdown,
		&i.SourceDocumentID,
		&i.IndexClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const documentByKey = `-- name: DocumentByKey :one
SELECT id, doc_key, doc_number, doc_number_norm, title, doc_type, doc_type_code, issuer, issuer_code, issued_at, signer, is_consolidated, markdown, source_document_id, index_class, created_at, updated_at FROM silver.document WHERE doc_key = $1
`

func (q *Queries) DocumentByKey(ctx context.Context, docKey string) (SilverDocument, error) {
	row := q.db.QueryRow(ctx, documentByKey, docKey)
	var i SilverDocument
	err := row.Scan(
		&i.ID,
		&i.DocKey,
		&i.DocNumber,
		&i.DocNumberNorm,
		&i.Title,
		&i.DocType,
		&i.DocTypeCode,
		&i.Issuer,
		&i.IssuerCode,
		&i.IssuedAt,
		&i.Signer,
		&i.IsConsolidated,
		&i.Markdown,
		&i.SourceDocumentID,
		&i.IndexClass,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const documentIDByAlias = `-- name: DocumentIDByAlias :one
SELECT document_id FROM silver.document_alias
WHERE source = $1 AND external_id = $2
`

type DocumentIDByAliasParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) DocumentIDByAlias(ctx context.Context, arg DocumentIDByAliasParams) (int64, error) {
	row := q.db.QueryRow(ctx, documentIDByAlias, arg.Source, arg.ExternalID)
	var document_id int64
	err := row.Scan(&document_id)
	return document_id, err
}

const documentIDsByNumberNorm = `-- name: DocumentIDsByNumberNorm :many
SELECT id FROM silver.document
WHERE doc_number_norm = $1 AND doc_number_norm <> ''
ORDER BY id
`

// Every document carrying a normalized số ký hiệu. More than one row means the
// bare number is ambiguous (distinct documents share it) and a number-only
// reference must not resolve.
func (q *Queries) DocumentIDsByNumberNorm(ctx context.Context, docNumberNorm string) ([]int64, error) {
	rows, err := q.db.Query(ctx, documentIDsByNumberNorm, docNumberNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBindingText = `-- name: GetBindingText :one
SELECT id, document_id, authority, source, raw_file_id, markdown, source_file_sha256, verbatim_sha256, is_binding, extract_engine, extract_confidence, needs_review, created_at, updated_at FROM silver.document_text
WHERE document_id = $1 AND is_binding = TRUE
ORDER BY
    CASE authority
        WHEN 'human_verified' THEN 1
        WHEN 'gazette_borndigital' THEN 2
        WHEN 'transcription_html' THEN 3
        WHEN 'ocr_extractive' THEN 4
        WHEN 'ocr_generative' THEN 5
        ELSE 99
    END,
    needs_review ASC,
    id
LIMIT 1
`

// Return the highest-authority binding text for a document (used by Normalize).
func (q *Queries) GetBindingText(ctx context.Context, documentID int64) (SilverDocumentText, error) {
	row := q.db.QueryRow(ctx, getBindingText, documentID)
	var i SilverDocumentText
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Authority,
		&i.Source,
		&i.RawFileID,
		&i.Markdown,
		&i.SourceFileSha256,
		&i.VerbatimSha256,
		&i.IsBinding,
		&i.ExtractEngine,
		&i.ExtractConfidence,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAmendmentEvent = `-- name: InsertAmendmentEvent :one
INSERT INTO silver.amendment_event (
    acting_document_id, target_ref_id, change_op, effective_date, source
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type InsertAmendmentEventParams struct {
	ActingDocumentID int64
	TargetRefID      int64
	ChangeOp         string
	EffectiveDate    *time.Time
	Source           *string
}

func (q *Queries) InsertAmendmentEvent(ctx context.Context, arg InsertAmendmentEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAmendmentEvent,
		arg.ActingDocumentID,
		arg.TargetRefID,
		arg.ChangeOp,
		arg.EffectiveDate,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertValidityPeriod = `-- name: InsertValidityPeriod :one
INSERT INTO silver.validity_period (
    document_id, section_id, version_id, status_code, status_class,
    eff_from, eff_to, reason, caused_by_ref_id, source, observed_at, superseded_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id
`

type InsertValidityPeriodParams struct {
	DocumentID    int64
	SectionID     *int64
	VersionID     *int64
	StatusCode    string
	StatusClass   string
	EffFrom       *time.Time
	EffTo         *time.Time
	Reason        *string
	CausedByRefID *int64
	Source        *string
	ObservedAt    time.Time
	SupersededAt  *time.Time
}

func (q *Queries) InsertValidityPeriod(ctx context.Context, arg InsertValidityPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertValidityPeriod,
		arg.DocumentID,
		arg.SectionID,
		arg.VersionID,
		arg.StatusCode,
		arg.StatusClass,
		arg.EffFrom,
		arg.EffTo,
		arg.Reason,
		arg.CausedByRefID,
		arg.Source,
		arg.ObservedAt,
		arg.SupersededAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAmendmentsTargeting = `-- name: ListAmendmentsTargeting :many
SELECT id, acting_document_id, target_ref_id, change_op, effective_date, source FROM silver.amendment_event
WHERE target_ref_id = $1
ORDER BY effective_date DESC NULLS LAST
`

func (q *Queries) ListAmendmentsTargeting(ctx context.Context, targetRefID int64) ([]SilverAmendmentEvent, error) {
	rows, err := q.db.Query(ctx, listAmendmentsTargeting, targetRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverAmendmentEvent
	for rows.Next() {
		var i SilverAmendmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActingDocumentID,
			&i.TargetRefID,
			&i.ChangeOp,
			&i.EffectiveDate,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, doc_key, doc_number, doc_number_norm, title, doc_type, doc_type_code, issuer, issuer_code, issued_at, signer, is_consolidated, markdown, source_document_id, index_class, created_at, updated_at FROM silver.document
ORDER BY issued_at DESC NULLS LAST, id DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]SilverDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocument
	for rows.Next() {
		var i SilverDocument
		if err := rows.Scan(
			&i.ID,
			&i.DocKey,
			&i.DocNumber,
			&i.DocNumberNorm,
			&i.Title,
			&i.DocType,
			&i.DocTypeCode,
			&i.Issuer,
			&i.IssuerCode,
			&i.IssuedAt,
			&i.Signer,
			&i.IsConsolidated,
			&i.Markdown,
			&i.SourceDocumentID,
			&i.IndexClass,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGazettesByDocument = `-- name: ListGazettesByDocument :many
SELECT id, document_id, gazette_number, gazette_date, source_document_id FROM silver.document_gazette
WHERE document_id = $1
ORDER BY gazette_date NULLS LAST, gazette_number
`

func (q *Queries) ListGazettesByDocument(ctx context.Context, documentID int64) ([]SilverDocumentGazette, error) {
	rows, err := q.db.Query(ctx, listGazettesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocumentGazette
	for rows.Next() {
		var i SilverDocumentGazette
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.GazetteNumber,
			&i.GazetteDate,
			&i.SourceDocumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationEvidenceByDocument = `-- name: ListRelationEvidenceByDocument :many
SELECT id, from_document_id, from_section_id, target_ref_id, evidence_key, evidence_kind, relation_type, relation_type_raw, operator, target_text, target_citation, citation, snippet, source, source_authority, confidence, promoted, created_at, updated_at FROM silver.relation_evidence
WHERE from_document_id = $1
ORDER BY promoted DESC, evidence_kind, relation_type, id
`

func (q *Queries) ListRelationEvidenceByDocument(ctx context.Context, fromDocumentID int64) ([]SilverRelationEvidence, error) {
	rows, err := q.db.Query(ctx, listRelationEvidenceByDocument, fromDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverRelationEvidence
	for rows.Next() {
		var i SilverRelationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.FromDocumentID,
			&i.FromSectionID,
			&i.TargetRefID,
			&i.EvidenceKey,
			&i.EvidenceKind,
			&i.RelationType,
			&i.RelationTypeRaw,
			&i.Operator,
			&i.TargetText,
			&i.TargetCitation,
			&i.Citation,
			&i.Snippet,
			&i.Source,
			&i.SourceAuthority,
			&i.Confidence,
			&i.Promoted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationEvidenceTo = `-- name: ListRelationEvidenceTo :many
SELECT id, from_document_id, from_section_id, target_ref_id, evidence_key, evidence_kind, relation_type, relation_type_raw, operator, target_text, target_citation, citation, snippet, source, source_authority, confidence, promoted, created_at, updated_at FROM silver.relation_evidence
WHERE target_ref_id = $1
ORDER BY promoted DESC, confidence DESC, id
`

func (q *Queries) ListRelationEvidenceTo(ctx context.Context, targetRefID int64) ([]SilverRelationEvidence, error) {
	rows, err := q.db.Query(ctx, listRelationEvidenceTo, targetRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverRelationEvidence
	for rows.Next() {
		var i SilverRelationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.FromDocumentID,
			&i.FromSectionID,
			&i.TargetRefID,
			&i.EvidenceKey,
			&i.EvidenceKind,
			&i.RelationType,
			&i.RelationTypeRaw,
			&i.Operator,
			&i.TargetText,
			&i.TargetCitation,
			&i.Citation,
			&i.Snippet,
			&i.Source,
			&i.SourceAuthority,
			&i.Confidence,
			&i.Promoted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsFrom = `-- name: ListRelationsFrom :many
SELECT id, from_document_id, to_ref_id, relation_type, relation_type_raw, from_section_id, to_citation, source FROM silver.document_relation
WHERE from_document_id = $1
`

func (q *Queries) ListRelationsFrom(ctx context.Context, fromDocumentID int64) ([]SilverDocumentRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsFrom, fromDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocumentRelation
	for rows.Next() {
		var i SilverDocumentRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromDocumentID,
			&i.ToRefID,
			&i.RelationType,
			&i.RelationTypeRaw,
			&i.FromSectionID,
			&i.ToCitation,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsTo = `-- name: ListRelationsTo :many
SELECT id, from_document_id, to_ref_id, relation_type, relation_type_raw, from_section_id, to_citation, source FROM silver.document_relation
WHERE to_ref_id = $1
`

func (q *Queries) ListRelationsTo(ctx context.Context, toRefID int64) ([]SilverDocumentRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsTo, toRefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocumentRelation
	for rows.Next() {
		var i SilverDocumentRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromDocumentID,
			&i.ToRefID,
			&i.RelationType,
			&i.RelationTypeRaw,
			&i.FromSectionID,
			&i.ToCitation,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByDocument = `-- name: ListSectionsByDocument :many
WITH RECURSIVE ordered AS (
    SELECT
        s.id, s.document_id, s.parent_id, s.node_key, s.ptype, s.kind, s.ordinal, s.label, s.heading, s.citation_path, s.content,
        ARRAY[LPAD(s.ordinal::text, 8, '0') || ':' || LPAD(s.id::text, 20, '0')] AS sort_path
    FROM silver.document_section s
    WHERE s.document_id = $1
      AND s.parent_id IS NULL

    UNION ALL

    SELECT
        child.id, child.document_id, child.parent_id, child.node_key, child.ptype, child.kind, child.ordinal, child.label, child.heading, child.citation_path, child.content,
        parent.sort_path || ARRAY[LPAD(child.ordinal::text, 8, '0') || ':' || LPAD(child.id::text, 20, '0')]
    FROM silver.document_section child
    JOIN ordered parent ON parent.id = child.parent_id
    WHERE child.document_id = $1
)
SELECT
    id, document_id, parent_id, node_key, ptype, kind, ordinal,
    label, heading, citation_path, content
FROM ordered
ORDER BY sort_path
`

type ListSectionsByDocumentRow struct {
	ID           int64
	DocumentID   int64
	ParentID     *int64
	NodeKey      *string
	Ptype        pgtype.Int2
	Kind         string
	Ordinal      int32
	Label        *string
	Heading      *string
	CitationPath string
	Content      *string
}

func (q *Queries) ListSectionsByDocument(ctx context.Context, documentID int64) ([]ListSectionsByDocumentRow, error) {
	rows, err := q.db.Query(ctx, listSectionsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionsByDocumentRow
	for rows.Next() {
		var i ListSectionsByDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParentID,
			&i.NodeKey,
			&i.Ptype,
			&i.Kind,
			&i.Ordinal,
			&i.Label,
			&i.Heading,
			&i.CitationPath,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextsByDocument = `-- name: ListTextsByDocument :many
SELECT id, document_id, authority, source, raw_file_id, markdown, source_file_sha256, verbatim_sha256, is_binding, extract_engine, extract_confidence, needs_review, created_at, updated_at FROM silver.document_text
WHERE document_id = $1
ORDER BY
    is_binding DESC,
    CASE authority
        WHEN 'human_verified' THEN 1
        WHEN 'gazette_borndigital' THEN 2
        WHEN 'transcription_html' THEN 3
        WHEN 'ocr_extractive' THEN 4
        WHEN 'ocr_generative' THEN 5
        ELSE 99
    END,
    needs_review ASC,
    id
`

// Texts for a document, best authority first; retrieval restricts binding answers
// to is_binding rows.
func (q *Queries) ListTextsByDocument(ctx context.Context, documentID int64) ([]SilverDocumentText, error) {
	rows, err := q.db.Query(ctx, listTextsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocumentText
	for rows.Next() {
		var i SilverDocumentText
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Authority,
			&i.Source,
			&i.RawFileID,
			&i.Markdown,
			&i.SourceFileSha256,
			&i.VerbatimSha256,
			&i.IsBinding,
			&i.ExtractEngine,
			&i.ExtractConfidence,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByDocument = `-- name: ListTopicsByDocument :many
SELECT id, document_id, topic, topic_source, matched_keyword, confidence FROM silver.document_topic
WHERE document_id = $1
ORDER BY topic
`

func (q *Queries) ListTopicsByDocument(ctx context.Context, documentID int64) ([]SilverDocumentTopic, error) {
	rows, err := q.db.Query(ctx, listTopicsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocumentTopic
	for rows.Next() {
		var i SilverDocumentTopic
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Topic,
			&i.TopicSource,
			&i.MatchedKeyword,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedStubs = `-- name: ListUnresolvedStubs :many
SELECT id, ref_key, document_id, label, src_ref, created_at, updated_at FROM silver.doc_ref
WHERE document_id IS NULL
ORDER BY id
LIMIT $1
`

// The out-of-corpus reference targets not yet ingested (the partial-index sweep).
func (q *Queries) ListUnresolvedStubs(ctx context.Context, limit int32) ([]SilverDocRef, error) {
	rows, err := q.db.Query(ctx, listUnresolvedStubs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocRef
	for rows.Next() {
		var i SilverDocRef
		if err := rows.Scan(
			&i.ID,
			&i.RefKey,
			&i.DocumentID,
			&i.Label,
			&i.SrcRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDocRef = `-- name: ResolveDocRef :exec
UPDATE silver.doc_ref
SET document_id = $2,
    updated_at = $3
WHERE ref_key = $1 AND document_id IS NULL
`

type ResolveDocRefParams struct {
	RefKey     string
	DocumentID *int64
	UpdatedAt  time.Time
}

// Link a stub to a now-ingested document. Run when a new document lands: every ref
// whose ref_key matches the new doc resolves with no rewrites to the edges that
// already point at it.
func (q *Queries) ResolveDocRef(ctx context.Context, arg ResolveDocRefParams) error {
	_, err := q.db.Exec(ctx, resolveDocRef, arg.RefKey, arg.DocumentID, arg.UpdatedAt)
	return err
}

const resolveDocRefForUniqueNumber = `-- name: ResolveDocRefForUniqueNumber :exec
UPDATE silver.doc_ref
SET document_id = $2,
    updated_at = $3
WHERE ref_key = $1
  AND document_id IS NULL
  AND (
      SELECT count(*) FROM silver.document d
      WHERE d.doc_number_norm = $4 AND d.doc_number_norm <> ''
  ) = 1
`

type ResolveDocRefForUniqueNumberParams struct {
	RefKey        string
	DocumentID    *int64
	UpdatedAt     time.Time
	DocNumberNorm string
}

// Link a number-keyed reference stub to a document, but only while exactly one
// document carries that normalized number. A bare số ký hiệu cannot pick
// between documents that share it (e.g. a Luật and a Nghị quyết numbered
// 51/2005/QH11), so ambiguous references stay stubs.
func (q *Queries) ResolveDocRefForUniqueNumber(ctx context.Context, arg ResolveDocRefForUniqueNumberParams) error {
	_, err := q.db.Exec(ctx, resolveDocRefForUniqueNumber,
		arg.RefKey,
		arg.DocumentID,
		arg.UpdatedAt,
		arg.DocNumberNorm,
	)
	return err
}

const setDocumentIndexClass = `-- name: SetDocumentIndexClass :exec
UPDATE silver.document
SET index_class = $2,
    updated_at = $3
WHERE id = $1
`

type SetDocumentIndexClassParams struct {
	ID         int64
	IndexClass string
	UpdatedAt  time.Time
}

// Records the Index-stage scope verdict ('primary' | 'relation_context').
func (q *Queries) SetDocumentIndexClass(ctx context.Context, arg SetDocumentIndexClassParams) error {
	_, err := q.db.Exec(ctx, setDocumentIndexClass, arg.ID, arg.IndexClass, arg.UpdatedAt)
	return err
}

const supersedeValidityPeriods = `-- name: SupersedeValidityPeriods :exec
UPDATE silver.validity_period
SET superseded_at = $2
WHERE document_id = $1 AND section_id IS NULL AND superseded_at IS NULL
`

type SupersedeValidityPeriodsParams struct {
	DocumentID   int64
	SupersededAt *time.Time
}

func (q *Queries) SupersedeValidityPeriods(ctx context.Context, arg SupersedeValidityPeriodsParams) error {
	_, err := q.db.Exec(ctx, supersedeValidityPeriods, arg.DocumentID, arg.SupersededAt)
	return err
}

const upsertDocRef = `-- name: UpsertDocRef :one
INSERT INTO silver.doc_ref (
    ref_key, document_id, label, src_ref, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $5
)
ON CONFLICT (ref_key) DO UPDATE SET
    document_id = COALESCE(silver.doc_ref.document_id, EXCLUDED.document_id),
    label = COALESCE(EXCLUDED.label, silver.doc_ref.label),
    src_ref = CASE
        WHEN COALESCE(silver.doc_ref.src_ref->>'source', '') = COALESCE(EXCLUDED.src_ref->>'source', '')
         AND COALESCE(silver.doc_ref.src_ref->>'target_id', '') <> ''
         AND COALESCE(silver.doc_ref.src_ref->>'target_id', '') = COALESCE(EXCLUDED.src_ref->>'target_id', '')
            THEN EXCLUDED.src_ref
        WHEN COALESCE(silver.doc_ref.src_ref->>'target_id', '') = ''
         AND COALESCE(EXCLUDED.src_ref->>'target_id', '') <> ''
            THEN EXCLUDED.src_ref
        ELSE COALESCE(silver.doc_ref.src_ref, EXCLUDED.src_ref)
    END,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertDocRefParams struct {
	RefKey     string
	DocumentID *int64
	Label      *string
	SrcRef     json.RawMessage
	CreatedAt  time.Time
}

// Idempotent on ref_key. Creating a reference target is safe whether or not the
// target is ingested yet: document_id stays NULL (a stub) until ResolveDocRef
// links it. COALESCE keeps an already-resolved ref from regressing to a stub.
func (q *Queries) UpsertDocRef(ctx context.Context, arg UpsertDocRefParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocRef,
		arg.RefKey,
		arg.DocumentID,
		arg.Label,
		arg.SrcRef,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO silver.document (
    doc_key, doc_number, doc_number_norm, title, doc_type, doc_type_code,
    issuer, issuer_code, issued_at, signer, is_consolidated, markdown,
    source_document_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $14
)
ON CONFLICT (doc_key) DO UPDATE SET
    doc_number = EXCLUDED.doc_number,
    doc_number_norm = EXCLUDED.doc_number_norm,
    title = EXCLUDED.title,
    doc_type = EXCLUDED.doc_type,
    doc_type_code = EXCLUDED.doc_type_code,
    issuer = EXCLUDED.issuer,
    issuer_code = EXCLUDED.issuer_code,
    issued_at = EXCLUDED.issued_at,
    signer = EXCLUDED.signer,
    is_consolidated = EXCLUDED.is_consolidated,
    markdown = COALESCE(EXCLUDED.markdown, silver.document.markdown),
    source_document_id = CASE
        WHEN EXCLUDED.markdown IS NOT NULL THEN EXCLUDED.source_document_id
        ELSE silver.document.source_document_id
    END,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertDocumentParams struct {
	DocKey           string
	DocNumber        *string
	DocNumberNorm    string
	Title            *string
	DocType          *string
	DocTypeCode      string
	Issuer           *string
	IssuerCode       string
	IssuedAt         *time.Time
	Signer           *string
	IsConsolidated   bool
	Markdown         *string
	SourceDocumentID *int64
	CreatedAt        time.Time
}

// Idempotent on the canonical doc_key so dedup re-runs converge on one logical doc.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.DocKey,
		arg.DocNumber,
		arg.DocNumberNorm,
		arg.Title,
		arg.DocType,
		arg.DocTypeCode,
		arg.Issuer,
		arg.IssuerCode,
		arg.IssuedAt,
		arg.Signer,
		arg.IsConsolidated,
		arg.Markdown,
		arg.SourceDocumentID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentAlias = `-- name: UpsertDocumentAlias :one
INSERT INTO silver.document_alias (
    source, external_id, document_id, match_method, confidence
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (source, external_id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    match_method = EXCLUDED.match_method,
    confidence = EXCLUDED.confidence
RETURNING id
`

type UpsertDocumentAliasParams struct {
	Source      string
	ExternalID  string
	DocumentID  int64
	MatchMethod string
	Confidence  pgtype.Float8
}

// Maps a source's (source, external_id) to the merged document; idempotent so the
// cross-source identity map can be rebuilt safely. match_method + confidence make
// the merge auditable.
func (q *Queries) UpsertDocumentAlias(ctx context.Context, arg UpsertDocumentAliasParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocumentAlias,
		arg.Source,
		arg.ExternalID,
		arg.DocumentID,
		arg.MatchMethod,
		arg.Confidence,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentGazette = `-- name: UpsertDocumentGazette :one
INSERT INTO silver.document_gazette (
    document_id, gazette_number, gazette_date, source_document_id
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (document_id, gazette_number) DO UPDATE SET
    gazette_date = EXCLUDED.gazette_date,
    source_document_id = EXCLUDED.source_document_id
RETURNING id
`

type UpsertDocumentGazetteParams struct {
	DocumentID       int64
	GazetteNumber    string
	GazetteDate      *time.Time
	SourceDocumentID *int64
}

// Idempotent on (document_id, gazette_number); a doc may appear in many issues.
func (q *Queries) UpsertDocumentGazette(ctx context.Context, arg UpsertDocumentGazetteParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocumentGazette,
		arg.DocumentID,
		arg.GazetteNumber,
		arg.GazetteDate,
		arg.SourceDocumentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentRelation = `-- name: UpsertDocumentRelation :one
INSERT INTO silver.document_relation (
    from_document_id, to_ref_id, relation_type, relation_type_raw,
    from_section_id, to_citation, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (from_document_id, to_ref_id, relation_type) DO UPDATE SET
    relation_type_raw = EXCLUDED.relation_type_raw,
    from_section_id = EXCLUDED.from_section_id,
    to_citation = EXCLUDED.to_citation,
    source = EXCLUDED.source
RETURNING id
`

type UpsertDocumentRelationParams struct {
	FromDocumentID  int64
	ToRefID         int64
	RelationType    string
	RelationTypeRaw *int32
	FromSectionID   *int64
	ToCitation      *string
	Source          *string
}

// Idempotent on (from_document_id, to_ref_id, relation_type) so the ingested
// reference graph converges. The target is a doc_ref (resolved or stub).
func (q *Queries) UpsertDocumentRelation(ctx context.Context, arg UpsertDocumentRelationParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocumentRelation,
		arg.FromDocumentID,
		arg.ToRefID,
		arg.RelationType,
		arg.RelationTypeRaw,
		arg.FromSectionID,
		arg.ToCitation,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentText = `-- name: UpsertDocumentText :one
INSERT INTO silver.document_text (
    document_id, authority, source, raw_file_id, markdown,
    source_file_sha256, verbatim_sha256, is_binding,
    extract_engine, extract_confidence, needs_review, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12
)
ON CONFLICT (document_id, authority, source) DO UPDATE SET
    raw_file_id = EXCLUDED.raw_file_id,
    markdown = EXCLUDED.markdown,
    source_file_sha256 = EXCLUDED.source_file_sha256,
    verbatim_sha256 = EXCLUDED.verbatim_sha256,
    is_binding = EXCLUDED.is_binding,
    extract_engine = EXCLUDED.extract_engine,
    extract_confidence = EXCLUDED.extract_confidence,
    needs_review = EXCLUDED.needs_review,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertDocumentTextParams struct {
	DocumentID        int64
	Authority         string
	Source            string
	RawFileID         *int64
	Markdown          *string
	SourceFileSha256  *string
	VerbatimSha256    *string
	IsBinding         bool
	ExtractEngine     *string
	ExtractConfidence pgtype.Float8
	NeedsReview       bool
	CreatedAt         time.Time
}

// Idempotent on (document_id, authority, source) so re-extraction with the same
// engine/source converges instead of stacking text rows.
func (q *Queries) UpsertDocumentText(ctx context.Context, arg UpsertDocumentTextParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocumentText,
		arg.DocumentID,
		arg.Authority,
		arg.Source,
		arg.RawFileID,
		arg.Markdown,
		arg.SourceFileSha256,
		arg.VerbatimSha256,
		arg.IsBinding,
		arg.ExtractEngine,
		arg.ExtractConfidence,
		arg.NeedsReview,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentTopic = `-- name: UpsertDocumentTopic :exec
INSERT INTO silver.document_topic (
    document_id, topic, topic_source, matched_keyword, confidence
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (document_id, topic, topic_source) DO UPDATE SET
    matched_keyword = EXCLUDED.matched_keyword,
    confidence = EXCLUDED.confidence
`

type UpsertDocumentTopicParams struct {
	DocumentID     int64
	Topic          string
	TopicSource    string
	MatchedKeyword *string
	Confidence     pgtype.Float8
}

func (q *Queries) UpsertDocumentTopic(ctx context.Context, arg UpsertDocumentTopicParams) error {
	_, err := q.db.Exec(ctx, upsertDocumentTopic,
		arg.DocumentID,
		arg.Topic,
		arg.TopicSource,
		arg.MatchedKeyword,
		arg.Confidence,
	)
	return err
}

const upsertRelationEvidence = `-- name: UpsertRelationEvidence :one
INSERT INTO silver.relation_evidence (
    from_document_id, from_section_id, target_ref_id, evidence_key,
    evidence_kind, relation_type, relation_type_raw, operator,
    target_text, target_citation, citation, snippet, source,
    source_authority, confidence, promoted, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $17
)
ON CONFLICT (from_document_id, evidence_key) DO UPDATE SET
    from_section_id = EXCLUDED.from_section_id,
    target_ref_id = EXCLUDED.target_ref_id,
    evidence_kind = EXCLUDED.evidence_kind,
    relation_type = EXCLUDED.relation_type,
    relation_type_raw = EXCLUDED.relation_type_raw,
    operator = EXCLUDED.operator,
    target_text = EXCLUDED.target_text,
    target_citation = EXCLUDED.target_citation,
    citation = EXCLUDED.citation,
    snippet = EXCLUDED.snippet,
    source = EXCLUDED.source,
    source_authority = EXCLUDED.source_authority,
    confidence = EXCLUDED.confidence,
    promoted = EXCLUDED.promoted,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertRelationEvidenceParams struct {
	FromDocumentID  int64
	FromSectionID   *int64
	TargetRefID     int64
	EvidenceKey     string
	EvidenceKind    string
	RelationType    string
	RelationTypeRaw *int32
	Operator        string
	TargetText      string
	TargetCitation  *string
	Citation        string
	Snippet         string
	Source          string
	SourceAuthority string
	Confidence      float64
	Promoted        bool
	CreatedAt       time.Time
}

func (q *Queries) UpsertRelationEvidence(ctx context.Context, arg UpsertRelationEvidenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRelationEvidence,
		arg.FromDocumentID,
		arg.FromSectionID,
		arg.TargetRefID,
		arg.EvidenceKey,
		arg.EvidenceKind,
		arg.RelationType,
		arg.RelationTypeRaw,
		arg.Operator,
		arg.TargetText,
		arg.TargetCitation,
		arg.Citation,
		arg.Snippet,
		arg.Source,
		arg.SourceAuthority,
		arg.Confidence,
		arg.Promoted,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSection = `-- name: UpsertSection :one
INSERT INTO silver.document_section (
    document_id, parent_id, node_key, ptype, kind, ordinal,
    label, heading, citation_path, content
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (document_id, citation_path) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    node_key = EXCLUDED.node_key,
    ptype = EXCLUDED.ptype,
    kind = EXCLUDED.kind,
    ordinal = EXCLUDED.ordinal,
    label = EXCLUDED.label,
    heading = EXCLUDED.heading,
    content = EXCLUDED.content
RETURNING id
`

type UpsertSectionParams struct {
	DocumentID   int64
	ParentID     *int64
	NodeKey      *string
	Ptype        pgtype.Int2
	Kind         string
	Ordinal      int32
	Label        *string
	Heading      *string
	CitationPath string
	Content      *string
}

// Idempotent on (document_id, citation_path) so re-parsing the provision tree
// converges. parent_id is resolved by the caller before insert.
func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSection,
		arg.DocumentID,
		arg.ParentID,
		arg.NodeKey,
		arg.Ptype,
		arg.Kind,
		arg.Ordinal,
		arg.Label,
		arg.Heading,
		arg.CitationPath,
		arg.Content,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
