-- +goose Up
-- Add new schema named "config"
CREATE SCHEMA IF NOT EXISTS "config";
-- Create "discovery_keyword" table
CREATE TABLE "config"."discovery_keyword" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "term" text NOT NULL, "source" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_discovery_keyword" UNIQUE ("source", "term"), CONSTRAINT "chk_config_discovery_keyword_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create "issuer_code" table
CREATE TABLE "config"."issuer_code" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "source" text NOT NULL, "code" text NOT NULL, "name" text NOT NULL DEFAULT '', "in_scope" boolean NOT NULL DEFAULT false, "is_sbv" boolean NOT NULL DEFAULT false, "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_issuer_code" UNIQUE ("source", "code"), CONSTRAINT "chk_config_issuer_code_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create "scope_term" table
CREATE TABLE "config"."scope_term" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "term" text NOT NULL, "term_class" text NOT NULL, "theme" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "enabled" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_scope_term" UNIQUE ("term_class", "term"), CONSTRAINT "chk_config_scope_term_class" CHECK (term_class = ANY (ARRAY['strong'::text, 'strong_title'::text, 'weak'::text, 'signal'::text])), CONSTRAINT "chk_config_scope_term_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create "setting" table
CREATE TABLE "config"."setting" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "key" text NOT NULL, "value" text NOT NULL, "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_setting" UNIQUE ("key"), CONSTRAINT "chk_config_setting_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
