// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgold

import (
	"context"
)

type Querier interface {
	ChunkByID(ctx context.Context, id int64) (GoldChunk, error)
	DeleteChunksByDocument(ctx context.Context, documentID int64) (int64, error)
	DocumentSummaryByDocument(ctx context.Context, documentID int64) (GoldDocumentSummary, error)
	ListChunksByDocument(ctx context.Context, documentID int64) ([]GoldChunk, error)
	// Cosine ANN over the HNSW index for one model, returning the chunk text and its
	// citation. The in-force pre-filter and BM25/RRF fusion are layered on in pkg/rag;
	// this is the vector leg of hybrid retrieval.
	SearchChunksByEmbedding(ctx context.Context, arg SearchChunksByEmbeddingParams) ([]SearchChunksByEmbeddingRow, error)
	// Idempotent on (document_id, citation, ordinal) so re-chunking converges.
	UpsertChunk(ctx context.Context, arg UpsertChunkParams) (int64, error)
	// Keyed by (chunk_id, model, dims) so multiple embedders coexist and re-embedding
	// a chunk overwrites only that model's vector.
	UpsertChunkEmbedding(ctx context.Context, arg UpsertChunkEmbeddingParams) (int64, error)
	UpsertDocumentSummary(ctx context.Context, arg UpsertDocumentSummaryParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
