// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgold

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const chunkByID = `-- name: ChunkByID :one
SELECT id, document_id, document_version_id, section_id, citation, context_prefix, content, ordinal, token_count FROM gold.chunk WHERE id = $1
`

func (q *Queries) ChunkByID(ctx context.Context, id int64) (GoldChunk, error) {
	row := q.db.QueryRow(ctx, chunkByID, id)
	var i GoldChunk
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.DocumentVersionID,
		&i.SectionID,
		&i.Citation,
		&i.ContextPrefix,
		&i.Content,
		&i.Ordinal,
		&i.TokenCount,
	)
	return i, err
}

const deleteChunksByDocument = `-- name: DeleteChunksByDocument :execrows
DELETE FROM gold.chunk WHERE document_id = $1
`

func (q *Queries) DeleteChunksByDocument(ctx context.Context, documentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChunksByDocument, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const documentSummaryByDocument = `-- name: DocumentSummaryByDocument :one
SELECT id, document_id, summary FROM gold.document_summary WHERE document_id = $1
`

func (q *Queries) DocumentSummaryByDocument(ctx context.Context, documentID int64) (GoldDocumentSummary, error) {
	row := q.db.QueryRow(ctx, documentSummaryByDocument, documentID)
	var i GoldDocumentSummary
	err := row.Scan(&i.ID, &i.DocumentID, &i.Summary)
	return i, err
}

const listChunksByDocument = `-- name: ListChunksByDocument :many
SELECT id, document_id, document_version_id, section_id, citation, context_prefix, content, ordinal, token_count FROM gold.chunk
WHERE document_id = $1
ORDER BY ordinal
`

func (q *Queries) ListChunksByDocument(ctx context.Context, documentID int64) ([]GoldChunk, error) {
	rows, err := q.db.Query(ctx, listChunksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoldChunk
	for rows.Next() {
		var i GoldChunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentVersionID,
			&i.SectionID,
			&i.Citation,
			&i.ContextPrefix,
			&i.Content,
			&i.Ordinal,
			&i.TokenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChunksByEmbedding = `-- name: SearchChunksByEmbedding :many
SELECT
    c.id,
    c.document_id,
    c.citation,
    c.context_prefix,
    c.content,
    e.embedding <=> $1 AS distance
FROM gold.chunk_embedding e
JOIN gold.chunk c ON c.id = e.chunk_id
WHERE e.model = $2
ORDER BY e.embedding <=> $1
LIMIT $3
`

type SearchChunksByEmbeddingParams struct {
	QueryEmbedding pgvector.Vector
	Model          string
	ResultLimit    int32
}

type SearchChunksByEmbeddingRow struct {
	ID            int64
	DocumentID    int64
	Citation      string
	ContextPrefix *string
	Content       string
	Distance      interface{}
}

// Cosine ANN over the HNSW index for one model, returning the chunk text and its
// citation. The in-force pre-filter and BM25/RRF fusion are layered on in pkg/rag;
// this is the vector leg of hybrid retrieval.
func (q *Queries) SearchChunksByEmbedding(ctx context.Context, arg SearchChunksByEmbeddingParams) ([]SearchChunksByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchChunksByEmbedding, arg.QueryEmbedding, arg.Model, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksByEmbeddingRow
	for rows.Next() {
		var i SearchChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Citation,
			&i.ContextPrefix,
			&i.Content,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChunk = `-- name: UpsertChunk :one
INSERT INTO gold.chunk (
    document_id, document_version_id, section_id, citation,
    context_prefix, content, ordinal, token_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (document_id, citation, ordinal) DO UPDATE SET
    document_version_id = EXCLUDED.document_version_id,
    section_id = EXCLUDED.section_id,
    context_prefix = EXCLUDED.context_prefix,
    content = EXCLUDED.content,
    token_count = EXCLUDED.token_count
RETURNING id
`

type UpsertChunkParams struct {
	DocumentID        int64
	DocumentVersionID *int64
	SectionID         *int64
	Citation          string
	ContextPrefix     *string
	Content           string
	Ordinal           int32
	TokenCount        *int32
}

// Idempotent on (document_id, citation, ordinal) so re-chunking converges.
func (q *Queries) UpsertChunk(ctx context.Context, arg UpsertChunkParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertChunk,
		arg.DocumentID,
		arg.DocumentVersionID,
		arg.SectionID,
		arg.Citation,
		arg.ContextPrefix,
		arg.Content,
		arg.Ordinal,
		arg.TokenCount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertChunkEmbedding = `-- name: UpsertChunkEmbedding :one
INSERT INTO gold.chunk_embedding (chunk_id, model, dims, embedding)
VALUES ($1, $2, $3, $4)
ON CONFLICT (chunk_id, model, dims) DO UPDATE SET
    embedding = EXCLUDED.embedding
RETURNING id
`

type UpsertChunkEmbeddingParams struct {
	ChunkID   int64
	Model     string
	Dims      int32
	Embedding pgvector.Vector
}

// Keyed by (chunk_id, model, dims) so multiple embedders coexist and re-embedding
// a chunk overwrites only that model's vector.
func (q *Queries) UpsertChunkEmbedding(ctx context.Context, arg UpsertChunkEmbeddingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertChunkEmbedding,
		arg.ChunkID,
		arg.Model,
		arg.Dims,
		arg.Embedding,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocumentSummary = `-- name: UpsertDocumentSummary :one
INSERT INTO gold.document_summary (document_id, summary)
VALUES ($1, $2)
ON CONFLICT (document_id) DO UPDATE SET
    summary = EXCLUDED.summary
RETURNING id
`

type UpsertDocumentSummaryParams struct {
	DocumentID int64
	Summary    *string
}

func (q *Queries) UpsertDocumentSummary(ctx context.Context, arg UpsertDocumentSummaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocumentSummary, arg.DocumentID, arg.Summary)
	var id int64
	err := row.Scan(&id)
	return id, err
}
